/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package views;

import com.mycompany.ecoactivistas.controller.ActivistaController;
import javax.swing.JOptionPane;

/**
 *
 * @author valeria
 */
public class FrmActivistas extends javax.swing.JPanel {

    
    ActivistaController aController;
    /**
     * Creates new form FrmActivistas
     */
    public FrmActivistas() {
        initComponents();
        aController = new ActivistaController();
        cargarActivistas();
        btnEliminar.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblActivistas = new javax.swing.JLabel();
        lblTituloRegistroActivista = new javax.swing.JLabel();
        lblIdAct = new javax.swing.JLabel();
        lblNombreAct = new javax.swing.JLabel();
        lblCorreoAct = new javax.swing.JLabel();
        lblFechaAct = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        txtTelefono = new javax.swing.JTextField();
        dcFechaIngreso = new com.toedter.calendar.JDateChooser();
        btnGuardar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        scrlActivistas = new javax.swing.JScrollPane();
        tblActivistas = new javax.swing.JTable();
        txtBuscar = new javax.swing.JTextField();
        btnEliminar = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        lblActivistas.setBackground(new java.awt.Color(255, 255, 255));
        lblActivistas.setFont(new java.awt.Font(".AppleSystemUIFont", 1, 15)); // NOI18N
        lblActivistas.setText("Administracion Activistas");

        lblTituloRegistroActivista.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        lblTituloRegistroActivista.setText("Registrar Activista");

        lblIdAct.setText("ID Activista:");

        lblNombreAct.setText("Nombre:");

        lblCorreoAct.setText("Telefono:");

        lblFechaAct.setText("Fecha Ingreso:");

        txtId.setEditable(false);
        txtId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdActionPerformed(evt);
            }
        });

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        tblActivistas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tblActivistas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblActivistasMouseClicked(evt);
            }
        });
        scrlActivistas.setViewportView(tblActivistas);

        txtBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBuscarActionPerformed(evt);
            }
        });
        txtBuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtBuscarKeyReleased(evt);
            }
        });

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblFechaAct)
                            .addComponent(lblNombreAct)
                            .addComponent(lblIdAct)
                            .addComponent(lblCorreoAct))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dcFechaIngreso, javax.swing.GroupLayout.DEFAULT_SIZE, 143, Short.MAX_VALUE)
                            .addComponent(txtTelefono)
                            .addComponent(txtNombre)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(123, 123, 123)
                        .addComponent(lblTituloRegistroActivista)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(scrlActivistas, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(61, 61, 61))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(175, 175, 175)
                        .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(112, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addComponent(btnGuardar)
                .addGap(73, 73, 73)
                .addComponent(btnCancelar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnEliminar)
                .addGap(182, 182, 182))
            .addGroup(layout.createSequentialGroup()
                .addGap(288, 288, 288)
                .addComponent(lblActivistas)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(86, 86, 86)
                .addComponent(lblTituloRegistroActivista)
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblIdAct)
                    .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombreAct)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblCorreoAct)
                    .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblFechaAct)
                    .addComponent(dcFechaIngreso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGuardar)
                    .addComponent(btnCancelar)
                    .addComponent(btnEliminar))
                .addGap(45, 45, 45))
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(lblActivistas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(scrlActivistas, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(94, 94, 94))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        guardarActivista();
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        limpiarFormulario();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void tblActivistasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblActivistasMouseClicked
        cargarDatos();
    }//GEN-LAST:event_tblActivistasMouseClicked

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        eliminarActivista();
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void txtBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBuscarActionPerformed
       
    }//GEN-LAST:event_txtBuscarActionPerformed

    private void txtBuscarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscarKeyReleased
        buscar();
    }//GEN-LAST:event_txtBuscarKeyReleased


    private void cargarActivistas(){
        tblActivistas.setModel(aController.obtenerTablaActivistas()); // -- Desde el controlador. Metodo obtenerTablaClientes()
        // Ese valor del metodo se setea en la tabla
    }
    
    private void guardarActivista(){
        try {
            String nombre = txtNombre.getText().trim();
            String telefono = txtTelefono.getText().trim();
            java.util.Date fecha = dcFechaIngreso.getDate();

            // Validación front-end
            if(nombre.isEmpty() || fecha == null || telefono.isEmpty()){
                JOptionPane.showMessageDialog(this,
                        "Nombre, telefono y fecha de ingreso son obligatorios",
                        "Error",
                        JOptionPane.WARNING_MESSAGE
                );
                return;
            }

            // Convertir a java.sql.Date
            java.sql.Date fechaSql = new java.sql.Date(fecha.getTime());

            if(btnGuardar.getText().equals("Guardar")){

                boolean exito = aController.agregarActivista(nombre, telefono, fechaSql);

                if(exito){
                    JOptionPane.showMessageDialog(this, "Activista agregado con éxito");
                    cargarActivistas();
                } else {
                    JOptionPane.showMessageDialog(this,
                            "Ocurrió un error al guardar el activista",
                            "Error",
                            JOptionPane.ERROR_MESSAGE
                    );
                }
            }

            if(btnGuardar.getText().equals("Actualizar")){

                int id = Integer.parseInt(txtId.getText());

                boolean exito = aController.actualizarActivista(id, nombre, telefono, fechaSql);

                if(exito){
                    JOptionPane.showMessageDialog(this, "Activista actualizado correctamente");
                    cargarActivistas();
                } else {
                    JOptionPane.showMessageDialog(this,
                            "Ocurrió un error al actualizar el activista",
                            "Error",
                            JOptionPane.ERROR_MESSAGE
                    );
                }
            }

            limpiarFormulario();

        } catch(Exception ex){
            JOptionPane.showMessageDialog(this,
                    "Error: " + ex.getMessage(),
                    "Error",
                    JOptionPane.ERROR_MESSAGE
            );
        }
    }
    
    private void limpiarFormulario(){
        txtId.setText("");
        txtNombre.setText("");
        txtTelefono.setText("");
        dcFechaIngreso.setDate(null);
        txtBuscar.setText("");
        btnGuardar.setText("Guardar");
        btnEliminar.setVisible(false);
    }
    
    private void cargarDatos(){
        int fila = tblActivistas.getSelectedRow();
        if(fila >= 0){
            txtId.setText(tblActivistas.getValueAt(fila, 0).toString());
            txtNombre.setText(tblActivistas.getValueAt(fila, 1).toString());
            txtTelefono.setText(tblActivistas.getValueAt(fila, 2).toString());
            dcFechaIngreso.setDate((java.util.Date)tblActivistas.getValueAt(fila, 3));

            btnGuardar.setText("Actualizar");
            btnEliminar.setVisible(true);
        } 
    }
    
    private void eliminarActivista(){
        try {
            int id = Integer.parseInt(txtId.getText());

            int confirm = JOptionPane.showConfirmDialog(this, 
                    "¿Está seguro de querer eliminar al activista?",
                    "Confirmación eliminación", 
                    JOptionPane.YES_NO_OPTION);

            if(confirm == JOptionPane.YES_OPTION){

                boolean exito = aController.eliminarActivista(id);

                if(exito){
                    JOptionPane.showMessageDialog(this, "Activista eliminado con éxito");
                    cargarActivistas();
                    limpiarFormulario();
                } else {
                    JOptionPane.showMessageDialog(
                            this,
                            "Ocurrió un error inesperado",
                            "Error",
                            JOptionPane.ERROR_MESSAGE
                    );
                }
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,
                    "Error: " + e.getMessage(),
                    "Error",
                    JOptionPane.ERROR_MESSAGE
            );
        }
    }
    
    private void buscar(){
        String nombre = txtBuscar.getText().trim();
        if(nombre.isEmpty()){
            cargarActivistas();
        } else {
            tblActivistas.setModel(aController.obtenerTablaActivistasFiltrado(nombre));
        }
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGuardar;
    private com.toedter.calendar.JDateChooser dcFechaIngreso;
    private javax.swing.JLabel lblActivistas;
    private javax.swing.JLabel lblCorreoAct;
    private javax.swing.JLabel lblFechaAct;
    private javax.swing.JLabel lblIdAct;
    private javax.swing.JLabel lblNombreAct;
    private javax.swing.JLabel lblTituloRegistroActivista;
    private javax.swing.JScrollPane scrlActivistas;
    private javax.swing.JTable tblActivistas;
    private javax.swing.JTextField txtBuscar;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtTelefono;
    // End of variables declaration//GEN-END:variables
}
