/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package views;

import com.mycompany.ecoactivistas.controller.ActivistaController;
import com.mycompany.ecoactivistas.controller.ClienteController;
import com.mycompany.ecoactivistas.controller.ProblemaActivistaController;
import com.mycompany.ecoactivistas.controller.ProblemaController;
import com.mycompany.ecoactivistas.model.Activista;
import com.mycompany.ecoactivistas.model.Cliente;
// import java.sql.Date;
import java.util.Date;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;

/**
 *
 * @author valeria
 */
public class FrmProblemas extends javax.swing.JPanel {
    private Cliente cliente;
    private ClienteController clController;
    private ActivistaController acController;
    private ProblemaController pController;
    private ProblemaActivistaController paController;
    private Activista activista;
    /**
     * Creates new form FrmProblemas
     */
    public FrmProblemas() {
        initComponents();
        clController = new ClienteController();
        acController = new ActivistaController();
        pController = new ProblemaController();
        paController = new ProblemaActivistaController();
        
        cargarProblemas();
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea3 = new javax.swing.JTextArea();
        lblTitulo = new javax.swing.JLabel();
        lblId = new javax.swing.JLabel();
        lblDescripcion = new javax.swing.JLabel();
        lblFecha1 = new javax.swing.JLabel();
        lblFecha2 = new javax.swing.JLabel();
        lblEstado = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        btnGuardar = new javax.swing.JButton();
        txtId = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        taDescripcion = new javax.swing.JTextArea();
        txtCliente = new javax.swing.JTextField();
        btnCancelar = new javax.swing.JButton();
        lblRegistrarCliente = new javax.swing.JLabel();
        dcFechaInicio = new com.toedter.calendar.JDateChooser();
        dcFechaFin = new com.toedter.calendar.JDateChooser();
        cmbEstado = new javax.swing.JComboBox<>();
        btnClientes = new javax.swing.JButton();
        scrlPaneProblemas = new javax.swing.JScrollPane();
        tblProblemas = new javax.swing.JTable();
        txtBuscar = new javax.swing.JTextField();
        btnEliminar = new javax.swing.JButton();

        jLabel6.setText("jLabel6");

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jScrollPane2.setViewportView(jTextArea2);

        jTextArea3.setColumns(20);
        jTextArea3.setRows(5);
        jScrollPane3.setViewportView(jTextArea3);

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(705, 370));

        lblTitulo.setFont(new java.awt.Font(".AppleSystemUIFont", 1, 15)); // NOI18N
        lblTitulo.setText("Administracion Problemas");

        lblId.setText("ID:");

        lblDescripcion.setText("Descripcion:");

        lblFecha1.setText("Fecha Inicio:");

        lblFecha2.setText("Fecha Fin:");

        lblEstado.setText("Estado:");

        jLabel8.setText("Cliente:");

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        txtId.setEditable(false);
        txtId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdActionPerformed(evt);
            }
        });

        taDescripcion.setColumns(20);
        taDescripcion.setRows(5);
        jScrollPane1.setViewportView(taDescripcion);

        txtCliente.setEditable(false);
        txtCliente.setFont(new java.awt.Font("Helvetica Neue", 0, 10)); // NOI18N
        txtCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtClienteActionPerformed(evt);
            }
        });

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        lblRegistrarCliente.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        lblRegistrarCliente.setText("Registrar Problema");

        dcFechaInicio.setDateFormatString("dd/MM/yyyy");
        dcFechaInicio.setFont(new java.awt.Font("Helvetica Neue", 0, 8)); // NOI18N
        dcFechaInicio.setMaxSelectableDate(new java.util.Date(4102473600000L));
        dcFechaInicio.setMinSelectableDate(new java.util.Date(631180800000L));

        dcFechaFin.setDateFormatString("dd/MM/yyyy");
        dcFechaFin.setFont(new java.awt.Font("Helvetica Neue", 0, 8)); // NOI18N
        dcFechaFin.setMaxSelectableDate(new java.util.Date(4102473600000L));
        dcFechaFin.setMinSelectableDate(new java.util.Date(631180800000L));

        cmbEstado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pendiente", "Concluido", "Cancelado" }));
        cmbEstado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbEstadoActionPerformed(evt);
            }
        });

        btnClientes.setBackground(new java.awt.Color(240, 234, 227));
        btnClientes.setFont(new java.awt.Font("InaiMathi", 1, 13)); // NOI18N
        btnClientes.setText("Buscar cliente");
        btnClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClientesActionPerformed(evt);
            }
        });

        tblProblemas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tblProblemas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblProblemasMouseClicked(evt);
            }
        });
        scrlPaneProblemas.setViewportView(tblProblemas);

        txtBuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtBuscarKeyReleased(evt);
            }
        });

        btnEliminar.setText("Eliminar");
        btnEliminar.setToolTipText("");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblTitulo)
                .addGap(269, 269, 269))
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblId)
                            .addComponent(lblDescripcion))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(lblEstado)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cmbEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblFecha1)
                            .addComponent(lblFecha2)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(dcFechaInicio, javax.swing.GroupLayout.DEFAULT_SIZE, 134, Short.MAX_VALUE)
                                .addComponent(dcFechaFin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(scrlPaneProblemas, javax.swing.GroupLayout.PREFERRED_SIZE, 342, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(45, 45, 45))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(96, 96, 96))))
            .addGroup(layout.createSequentialGroup()
                .addGap(169, 169, 169)
                .addComponent(lblRegistrarCliente)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(150, 150, 150)
                .addComponent(btnGuardar)
                .addGap(18, 18, 18)
                .addComponent(btnCancelar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnEliminar)
                .addGap(172, 172, 172))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(lblTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addComponent(lblRegistrarCliente)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblId)
                            .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmbEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblEstado))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblDescripcion)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblFecha1)
                            .addComponent(dcFechaInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(lblFecha2))
                            .addComponent(dcFechaFin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnClientes))
                            .addComponent(jLabel8)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(scrlPaneProblemas, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(btnEliminar)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnGuardar)
                            .addComponent(btnCancelar))
                        .addGap(20, 20, 20))))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        guardarProblema();
    }//GEN-LAST:event_btnGuardarActionPerformed
 
    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        limpiarFormulario();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void txtIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdActionPerformed

    private void btnClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClientesActionPerformed
        JFrame frame = (JFrame) SwingUtilities.getWindowAncestor(this);
        dlgBuscarCliente dlg = new dlgBuscarCliente(frame, true); // modal
        dlg.setLocationRelativeTo(this);
        dlg.setVisible(true); // esto bloquea hasta cerrar el diálogo

        // Después de cerrar, obtener el cliente seleccionado
        Integer idCliente = dlg.getClienteSeleccionado();
        if (idCliente != null) {
            this.cliente = clController.obtenerCliente(idCliente);
            txtCliente.setText(this.cliente.getNombre());
        }      
    }//GEN-LAST:event_btnClientesActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        eliminarProblema();
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void cmbEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbEstadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbEstadoActionPerformed

    private void txtClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtClienteActionPerformed

    private void txtBuscarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscarKeyReleased
        buscar();
    }//GEN-LAST:event_txtBuscarKeyReleased

    private void tblProblemasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblProblemasMouseClicked
        cargarDatos();
    }//GEN-LAST:event_tblProblemasMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnClientes;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JComboBox<String> cmbEstado;
    private com.toedter.calendar.JDateChooser dcFechaFin;
    private com.toedter.calendar.JDateChooser dcFechaInicio;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextArea jTextArea3;
    private javax.swing.JLabel lblDescripcion;
    private javax.swing.JLabel lblEstado;
    private javax.swing.JLabel lblFecha1;
    private javax.swing.JLabel lblFecha2;
    private javax.swing.JLabel lblId;
    private javax.swing.JLabel lblRegistrarCliente;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JScrollPane scrlPaneProblemas;
    private javax.swing.JTextArea taDescripcion;
    private javax.swing.JTable tblProblemas;
    private javax.swing.JTextField txtBuscar;
    private javax.swing.JTextField txtCliente;
    private javax.swing.JTextField txtId;
    // End of variables declaration//GEN-END:variables

   
    
    private void guardarProblema() {
        try {
        
            String descripcion = taDescripcion.getText().trim(); 
            String estado = cmbEstado.getSelectedItem().toString().trim();

            Date fechaInicio = dcFechaInicio.getDate();
            Date fechaFin = dcFechaFin.getDate();
            
            if (descripcion.isEmpty() || fechaInicio == null || this.cliente == null) {
                JOptionPane.showMessageDialog(
                        this,
                        "Todos los campos son obligatorios (Menos la fecha fin).",
                        "Error",
                        JOptionPane.WARNING_MESSAGE
                );
                return;
            }

            /*
            java.sql.Date sqlDateInicio = new java.sql.Date(fechaInicio.getTime());
            java.sql.Date sqlDateFin = new java.sql.Date(fechaFin.getTime());
            */
            
            java.sql.Date sqlDateInicio = new java.sql.Date(fechaInicio.getTime());
            java.sql.Date sqlDateFin = null;
            if(fechaFin != null){
                sqlDateFin = new java.sql.Date(fechaFin.getTime());
            }
            

            if (btnGuardar.getText().equals("Guardar")) {

                // Ahora regresa boolean
                boolean exito = pController.agregarProblema(
                        sqlDateInicio,
                        sqlDateFin,
                        estado,
                        this.cliente.getIdCliente(),
                        descripcion
                );

                if (exito) {
                    JOptionPane.showMessageDialog(this, "Problema guardado correctamente.");
                    cargarProblemas();
                } else {
                    JOptionPane.showMessageDialog(
                            this,
                            "Ocurrió un error al guardar el problema.",
                            "Error",
                            JOptionPane.ERROR_MESSAGE
                    );
                }
            }
            
            if(btnGuardar.getText().equals("Actualizar")){
                int id = Integer.parseInt(txtId.getText());
                int idCliente = this.cliente.getIdCliente();

                boolean exito = pController.actualizarProblema(id, sqlDateInicio, sqlDateFin, estado, idCliente, descripcion);
                if (exito) {
                    JOptionPane.showMessageDialog(this, "Problema actualizado correctamente.");
                    cargarProblemas(); // refrescar tabla
                } else {
                    JOptionPane.showMessageDialog(
                            this,
                            "Ocurrio un error al actualizar los datos del problema.",
                            "Error",
                            JOptionPane.ERROR_MESSAGE
                    );
                }
            }
            
            limpiarFormulario();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(
                    this,
                    "Error: " + e.getMessage(),
                    "Error",
                    JOptionPane.ERROR_MESSAGE
            );
        }
    }
    
    private void limpiarFormulario(){
        txtId.setText("");
        cmbEstado.setSelectedIndex(0);
        taDescripcion.setText("");
        dcFechaInicio.setDate(null);
        dcFechaFin.setDate(null);
        txtCliente.setText("");
        txtBuscar.setText("");
        btnGuardar.setText("Guardar");
        btnEliminar.setVisible(false);
    }
    
    private void buscar(){
        String descripcion = txtBuscar.getText().trim();
        if(descripcion.isEmpty()){
            cargarProblemas();
        } else {
            tblProblemas.setModel(pController.obtenerTablaProblemasFiltrado(descripcion));
        }
    }
    
    private void eliminarProblema(){
        try {
            int id = Integer.parseInt(txtId.getText());

            int confirm = JOptionPane.showConfirmDialog(this, 
                    "Esta seguro de querer eliminar el problema?",
                    "Confirmacion eliminacion", 
                    JOptionPane.YES_NO_OPTION);

            if(confirm == JOptionPane.YES_OPTION){
                boolean exito = pController.eliminarProblema(id);
               
                if(exito){
                    JOptionPane.showMessageDialog(this, "Problema eliminado con exito");
                    cargarProblemas();
                    limpiarFormulario();
                }else{
                    JOptionPane.showMessageDialog(
                            this,
                            "Ocurrio un error innesperado",
                            "Error",
                            JOptionPane.ERROR_MESSAGE
                    );
                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,
                    "Error: "+e.getMessage(),
                    "Error",
                    JOptionPane.ERROR_MESSAGE
            );
        } 
    }
    
    private void cargarProblemas(){
        tblProblemas.setModel(pController.obtenerTablaProblemas()); // -- Desde el controlador. Metodo obtenerTablaClientes()
        // Ese valor del metodo se setea en la tabla
    }
    
    private void cargarDatos(){
        int fila = tblProblemas.getSelectedRow();
        if(fila >= 0){
            txtId.setText(tblProblemas.getValueAt(fila, 0).toString());
            dcFechaInicio.setDate((java.util.Date) tblProblemas.getValueAt(fila, 1));
            dcFechaFin.setDate((java.util.Date) tblProblemas.getValueAt(fila, 2));
            cmbEstado.setSelectedItem(tblProblemas.getValueAt(fila, 3).toString());
            
            int idCliente = Integer.parseInt(tblProblemas.getValueAt(fila, 4).toString());
            this.cliente = clController.obtenerCliente(idCliente);

            txtCliente.setText(this.cliente.getNombre());
            taDescripcion.setText(tblProblemas.getValueAt(fila, 5).toString());

            btnGuardar.setText("Actualizar");
            btnEliminar.setVisible(true);
        }
    }

}
