/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package views;

import controllers.AnimalController;
import controllers.AsignacionController;
import controllers.VoluntarioController;
import enums.Actividad;
import java.sql.SQLException;
import java.util.Date;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import models.Animal;
import models.Asignacion;
import models.Voluntario;

/**
 *
 * @author valeria
 */
public class FrmAdminAsignaciones extends javax.swing.JFrame {
    
    private VoluntarioController vController;
    private AnimalController aController;
    private AsignacionController asController;    
    
    private Voluntario voluntario;
    private Animal animal;
    private Asignacion asignacion;
    
    private int idRefugio;
    private javax.swing.JFrame ventanaPadre;

    /**
     * Creates new form FrmAdminAsignaciones
     */
    public FrmAdminAsignaciones(javax.swing.JFrame ventanaPadre, int idRefugio) {
        initComponents();
        vController = new VoluntarioController();
        aController = new AnimalController();
        asController = new AsignacionController();
        this.idRefugio = idRefugio;
        
        cargarTablaAsignaciones(idRefugio);
        cargarComboActividades();
        
        btnEliminar.setVisible(false);
        this.setLocationRelativeTo(null); // Centra la ventana en la pantalla
        this.setResizable(false);
        this.ventanaPadre = ventanaPadre;
        
        
        // Convertir el entero a String para salarlo al txt
        int numero = idRefugio;
        String id2 = String.valueOf(numero);
        txtRefugio.setText(id2);
        
        txtID.setEnabled(false);
        txtRefugio.setEnabled(false);
        txtID.setEditable(false);
        txtRefugio.setEditable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlBase = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        lblSubRefugios = new javax.swing.JLabel();
        lblTituloAdminAs = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lblSubtituloRegistro = new javax.swing.JLabel();
        txtVoluntario = new javax.swing.JTextField();
        txtAnimal = new javax.swing.JTextField();
        txtRefugio = new javax.swing.JTextField();
        txtID = new javax.swing.JTextField();
        cmbActividad = new javax.swing.JComboBox<>();
        dcFecha = new com.toedter.calendar.JDateChooser();
        btnBuscarVoluntario = new javax.swing.JButton();
        btnBuscarAnimal = new javax.swing.JButton();
        btnRegistrar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        scrlTabla = new javax.swing.JScrollPane();
        tblAsignaciones = new javax.swing.JTable();
        txtFiltro = new javax.swing.JTextField();
        lblSubtituloFiltro = new javax.swing.JLabel();
        btnEliminar = new javax.swing.JButton();
        btnListo = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnlBase.setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        lblSubRefugios.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        lblSubRefugios.setForeground(new java.awt.Color(102, 102, 102));
        lblSubRefugios.setText("Refugios Cajeme");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(lblSubRefugios)
                .addContainerGap(741, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblSubRefugios)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        lblTituloAdminAs.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        lblTituloAdminAs.setForeground(new java.awt.Color(102, 102, 102));
        lblTituloAdminAs.setText("Administración Asignaciones");

        jLabel1.setText("ID:");

        jLabel2.setText("Fecha:");

        jLabel3.setText("Actividad:");

        jLabel4.setText("Voluntario:");

        jLabel5.setText("Animal:");

        jLabel6.setText("Refugio:");

        lblSubtituloRegistro.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        lblSubtituloRegistro.setForeground(new java.awt.Color(102, 102, 102));
        lblSubtituloRegistro.setText("Registrar una Asignacion");

        txtVoluntario.setEditable(false);

        txtAnimal.setEditable(false);

        txtRefugio.setEditable(false);
        txtRefugio.setBackground(new java.awt.Color(204, 204, 204));
        txtRefugio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRefugioActionPerformed(evt);
            }
        });

        txtID.setEditable(false);
        txtID.setBackground(new java.awt.Color(204, 204, 204));
        txtID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIDActionPerformed(evt);
            }
        });

        cmbActividad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        dcFecha.setDateFormatString("dd/MM/yyyy");

        btnBuscarVoluntario.setText("BUSCAR");
        btnBuscarVoluntario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarVoluntarioActionPerformed(evt);
            }
        });

        btnBuscarAnimal.setText("BUSCAR");
        btnBuscarAnimal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarAnimalActionPerformed(evt);
            }
        });

        btnRegistrar.setText("REGISTRAR");
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });

        btnCancelar.setText("CANCELAR");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        tblAsignaciones.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tblAsignaciones.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblAsignacionesMouseClicked(evt);
            }
        });
        scrlTabla.setViewportView(tblAsignaciones);

        txtFiltro.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtFiltroKeyReleased(evt);
            }
        });

        lblSubtituloFiltro.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        lblSubtituloFiltro.setForeground(new java.awt.Color(102, 102, 102));
        lblSubtituloFiltro.setText("------- Filtrar por Actividad -------");

        btnEliminar.setText("ELIMINAR");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        btnListo.setText("LISTO");
        btnListo.setToolTipText("");
        btnListo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlBaseLayout = new javax.swing.GroupLayout(pnlBase);
        pnlBase.setLayout(pnlBaseLayout);
        pnlBaseLayout.setHorizontalGroup(
            pnlBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pnlBaseLayout.createSequentialGroup()
                .addGap(94, 94, 94)
                .addGroup(pnlBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlBaseLayout.createSequentialGroup()
                        .addComponent(btnRegistrar)
                        .addGap(18, 18, 18)
                        .addComponent(btnCancelar)
                        .addGap(191, 191, 191)
                        .addComponent(btnEliminar)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(pnlBaseLayout.createSequentialGroup()
                        .addGroup(pnlBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblSubtituloRegistro)
                            .addComponent(dcFecha, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cmbActividad, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(pnlBaseLayout.createSequentialGroup()
                                .addGroup(pnlBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(txtRefugio, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 81, Short.MAX_VALUE)
                                    .addComponent(txtAnimal, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtVoluntario, javax.swing.GroupLayout.Alignment.LEADING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(pnlBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnBuscarVoluntario)
                                    .addComponent(btnBuscarAnimal)))
                            .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(pnlBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlBaseLayout.createSequentialGroup()
                                .addGroup(pnlBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(pnlBaseLayout.createSequentialGroup()
                                        .addComponent(lblSubtituloFiltro)
                                        .addGap(25, 25, 25)))
                                .addGap(133, 133, 133))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlBaseLayout.createSequentialGroup()
                                .addComponent(scrlTabla, javax.swing.GroupLayout.PREFERRED_SIZE, 403, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(49, 49, 49))))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlBaseLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnListo)
                .addGap(14, 14, 14))
            .addGroup(pnlBaseLayout.createSequentialGroup()
                .addGap(301, 301, 301)
                .addComponent(lblTituloAdminAs)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        pnlBaseLayout.setVerticalGroup(
            pnlBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBaseLayout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblTituloAdminAs)
                .addGap(30, 30, 30)
                .addGroup(pnlBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlBaseLayout.createSequentialGroup()
                        .addComponent(lblSubtituloRegistro)
                        .addGap(27, 27, 27)
                        .addGroup(pnlBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pnlBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(dcFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pnlBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cmbActividad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pnlBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtVoluntario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnBuscarVoluntario))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtAnimal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)
                            .addComponent(btnBuscarAnimal))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(txtRefugio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(pnlBaseLayout.createSequentialGroup()
                        .addComponent(lblSubtituloFiltro)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(scrlTabla, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(34, 34, 34)
                .addGroup(pnlBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRegistrar)
                    .addComponent(btnCancelar)
                    .addComponent(btnEliminar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnListo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlBase, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlBase, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtRefugioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRefugioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRefugioActionPerformed

    private void txtIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIDActionPerformed

    private void tblAsignacionesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblAsignacionesMouseClicked
        cargarDatosATxt();
    }//GEN-LAST:event_tblAsignacionesMouseClicked

    private void txtFiltroKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFiltroKeyReleased
        buscar();
    }//GEN-LAST:event_txtFiltroKeyReleased

    private void btnBuscarVoluntarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarVoluntarioActionPerformed
        JFrame frame = (JFrame) SwingUtilities.getWindowAncestor(this);
        dlgVoluntario dlg = new dlgVoluntario(frame, true); // modal
        dlg.setLocationRelativeTo(this);
        dlg.setVisible(true); // esto bloquea hasta cerrar el diálogo

        // Después de cerrar, obtener el cliente seleccionado
        Integer idVoluntario = dlg.getVoluntarioSeleccionado();
        if (idVoluntario != null) {
            this.voluntario = vController.obtenerVoluntario(idVoluntario);
            txtVoluntario.setText(String.valueOf(this.voluntario.getIdVoluntario()));
        }
    }//GEN-LAST:event_btnBuscarVoluntarioActionPerformed

    private void btnBuscarAnimalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarAnimalActionPerformed
        JFrame frame = (JFrame) SwingUtilities.getWindowAncestor(this);
        dlgAnimal dlg = new dlgAnimal(frame, true, idRefugio); // modal
        dlg.setLocationRelativeTo(this);
        dlg.setVisible(true); // esto bloquea hasta cerrar el diálogo

        // Después de cerrar, obtener el cliente seleccionado
        Integer idAnimal = dlg.getAnimalSeleccionado();
        if (idAnimal != null) {
            this.animal = aController.obtenerAnimal(idAnimal);
            txtAnimal.setText(String.valueOf(this.animal.getIdAnimal()));
        }
    }//GEN-LAST:event_btnBuscarAnimalActionPerformed
    
    private void btnListoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListoActionPerformed
        // 1. Cerramos el registro (se libera esta memoria)
        this.dispose(); 

        // 2. Usamos la referencia que guardamos para mostrar la original
        if (ventanaPadre != null) {
            ventanaPadre.setVisible(true);
        }
    }//GEN-LAST:event_btnListoActionPerformed

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
        guardarAsignacion();
    }//GEN-LAST:event_btnRegistrarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        limpiarFormulario();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        eliminarAsignacion();
    }//GEN-LAST:event_btnEliminarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscarAnimal;
    private javax.swing.JButton btnBuscarVoluntario;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnListo;
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JComboBox<Object> cmbActividad;
    private com.toedter.calendar.JDateChooser dcFecha;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblSubRefugios;
    private javax.swing.JLabel lblSubtituloFiltro;
    private javax.swing.JLabel lblSubtituloRegistro;
    private javax.swing.JLabel lblTituloAdminAs;
    private javax.swing.JPanel pnlBase;
    private javax.swing.JScrollPane scrlTabla;
    private javax.swing.JTable tblAsignaciones;
    private javax.swing.JTextField txtAnimal;
    private javax.swing.JTextField txtFiltro;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtRefugio;
    private javax.swing.JTextField txtVoluntario;
    // End of variables declaration//GEN-END:variables


    
    private void cargarTablaAsignaciones(int idRefugio) {
        tblAsignaciones.setModel(asController.obtenerTablaAsignaciones(idRefugio));
    }
    
    private void cargarComboActividades() {
       
        cmbActividad.removeAllItems();

        // 2. Agregamos el String de instrucción (será el índice 0)
        cmbActividad.addItem("Seleccione una opcion"); // Se tiene que cambiar el valor del cbm de String a object

        // 3. Agregamos los objetos reales del Enum
        for (Actividad e : Actividad.values()) {
            cmbActividad.addItem(e); 
        }
    }
    
    private void guardarAsignacion() {
        try {
            // 1. Validación de campos básicos (campos vacíos, etc.)
            if (!validarCampos()) {
                return; 
            }

            // 2. Validar que se haya seleccionado un Voluntario y un Animal
            // Usamos los objetos que cargaste en los métodos btnBuscar...
            if (this.voluntario == null || this.animal == null) {
                JOptionPane.showMessageDialog(this, "Debe seleccionar un voluntario y un animal.");
                return;
            }

            // 3. Obtener la Actividad del ComboBox
            Object seleccionado = cmbActividad.getSelectedItem();
            if (seleccionado instanceof String) {
                JOptionPane.showMessageDialog(this, "Por favor seleccione una actividad válida.");
                return;
            }
            Actividad actividad = (Actividad) seleccionado;

            // 4. Obtener la Fecha (asumiendo que usas un JDateChooser llamado dcFecha)
            Date fecha = dcFecha.getDate();
            if (fecha == null) {
                JOptionPane.showMessageDialog(this, "Debe seleccionar una fecha.");
                return;
            }
            java.sql.Date sqlFecha = new java.sql.Date(fecha.getTime());

            // 5. Lógica para GUARDAR (Insertar)
            if (btnRegistrar.getText().equals("REGISTRAR")) {
                // Pasamos los IDs de los objetos cargados y la actividad
                boolean exito = asController.agregarAsignacion(
                    sqlFecha, 
                    actividad, 
                    this.animal.getIdAnimal(), 
                    this.voluntario.getIdVoluntario()
                );

                if (exito) {
                    JOptionPane.showMessageDialog(this, "Asignación registrada con éxito");
                    cargarTablaAsignaciones(idRefugio); 
                    limpiarFormulario();
                } else {
                    JOptionPane.showMessageDialog(this, "Error al guardar la asignación", "Error", JOptionPane.ERROR_MESSAGE);
                }
            } 

            // 6. Lógica para ACTUALIZAR
            else if (btnRegistrar.getText().equals("ACTUALIZAR")) {
                int idAsignacion = Integer.parseInt(txtID.getText().trim()); 

                boolean exito = asController.editarAsignacion(
                    idAsignacion, 
                    sqlFecha, 
                    actividad, 
                    this.animal.getIdAnimal(), 
                    this.voluntario.getIdVoluntario()
                );

                if (exito) {
                    JOptionPane.showMessageDialog(this, "Asignación actualizada.");
                    cargarTablaAsignaciones(idRefugio);
                    limpiarFormulario();
                } else {
                    JOptionPane.showMessageDialog(this, "Error al actualizar.", "Error", JOptionPane.ERROR_MESSAGE);
                }
            }

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Error: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            ex.printStackTrace();
        }
    }

    private boolean validarCampos() {
        if ( 
            cmbActividad.getSelectedIndex() <= 0 || 
            txtVoluntario.getText().trim().isEmpty() || 
            txtAnimal.getText().trim().isEmpty()) {

            JOptionPane.showMessageDialog(this, "Todos los campos son requeridos", "Formulario Vacío", JOptionPane.WARNING_MESSAGE);
            return false;
        }
        // Validar Fecha (JDateChooser)
        if (dcFecha.getDate() == null) {
            JOptionPane.showMessageDialog(this, "Debe seleccionar una fecha válida.", "Validación", JOptionPane.WARNING_MESSAGE);
            dcFecha.requestFocusInWindow();
            return false;
        }
        
        // Validar Fecha de Nacimiento (Razonable: que no sea hoy ni en el futuro)
        java.util.Date fechaSeleccionada = dcFecha.getDate();
        java.util.Date hoy = new java.util.Date();
        if (fechaSeleccionada.before(hoy)) {
            JOptionPane.showMessageDialog(this, "La fecha de asignacion no puede ser anterior.");
            return false;
        }

        // Verifica que no esté en el índice 0 ("Seleccione una opcion")
        if (cmbActividad.getSelectedIndex() <= 0) {
            JOptionPane.showMessageDialog(this, "Por favor, seleccione una actividad de la lista.", "Validación", JOptionPane.WARNING_MESSAGE);
            cmbActividad.requestFocusInWindow();
            return false;
        }

        // 3. Validar Selección de Voluntario y Animal (Objetos y Regex de ID)
        // Usamos Regex para asegurar que lo que está en el TXT sea un número, 
        // pero lo más importante es que el objeto global no sea null.
        String regexID = "^[0-9]+$"; // Solo números

        if (this.voluntario == null || !txtVoluntario.getText().matches(regexID)) {
            JOptionPane.showMessageDialog(this, "Debe buscar y seleccionar un Voluntario válido.", "Validación", JOptionPane.WARNING_MESSAGE);
            btnBuscarVoluntario.requestFocusInWindow();
            return false;
        }

        if (this.animal == null || !txtAnimal.getText().matches(regexID)) {
            JOptionPane.showMessageDialog(this, "Debe buscar y seleccionar un Animal válido.", "Validación", JOptionPane.WARNING_MESSAGE);
            btnBuscarAnimal.requestFocusInWindow();
            return false;
        }

        return true;
    }
    
    private void limpiarFormulario(){
        txtID.setText("");
        dcFecha.setDate(null);
        cmbActividad.setSelectedIndex(0);
        txtVoluntario.setText("");
        txtAnimal.setText("");
        txtFiltro.setText("");
        btnRegistrar.setText("REGISTRAR");
        btnEliminar.setVisible(false);
    }
    
    private void cargarDatosATxt(){
        int fila = tblAsignaciones.getSelectedRow();
        if(fila>=0){
            txtID.setText(tblAsignaciones.getValueAt(fila, 0).toString());
            dcFecha.setDate((java.util.Date) tblAsignaciones.getValueAt(fila, 1));
            cmbActividad.setSelectedItem(tblAsignaciones.getValueAt(fila, 2));
            
            
            // 4. Cargamos los IDs de Animal y Voluntario en los campos de texto
            int idAnimal = (int) tblAsignaciones.getValueAt(fila, 3);
            int idVoluntario = (int) tblAsignaciones.getValueAt(fila, 5);

            txtAnimal.setText(String.valueOf(idAnimal));
            txtVoluntario.setText(String.valueOf(idVoluntario));

            // 5. IMPORTANTE: Debemos actualizar los objetos globales 'animal' y 'voluntario'
            // Esto es necesario porque tu método 'guardarAsignacion' usa 'this.animal' y 'this.voluntario'
            this.animal = aController.obtenerAnimal(idAnimal);
            this.voluntario = vController.obtenerVoluntario(idVoluntario);

            btnRegistrar.setText("ACTUALIZAR");
            btnEliminar.setVisible(true);
        }
    }
    
    private void buscar(){
        String actividad = txtFiltro.getText().trim();
        if(actividad.isEmpty()){
            cargarTablaAsignaciones(idRefugio);
        } else {
            tblAsignaciones.setModel(asController.obtenerTablaAsignacionesFiltroActividad(actividad, idRefugio));
        }
    }
    
    
    private void eliminarAsignacion() {
        try {
            if (txtID.getText().trim().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Debe seleccionar una asignación de la tabla para eliminar.");
                return;
            }

            int id = Integer.parseInt(txtID.getText().trim());

            // 2. Pedir confirmación al usuario
            int confirm = JOptionPane.showConfirmDialog(this, 
                    "¿Está seguro de querer eliminar esta asignación?",
                    "Confirmación de eliminación", 
                    JOptionPane.YES_NO_OPTION);

            if (confirm == JOptionPane.YES_OPTION) {

                try {
                    // 3. Llamar al controlador de asignaciones
                    boolean exito = asController.eliminarAsignacion(id);

                    if (exito) {
                        JOptionPane.showMessageDialog(this, "Asignación eliminada con éxito");
                        cargarTablaAsignaciones(idRefugio); // Actualiza la tabla con los JOINs
                        limpiarFormulario();      // Limpia campos y oculta el botón eliminar
                    } else {
                        JOptionPane.showMessageDialog(
                                this,
                                "No se encontró la asignación a eliminar",
                                "Error",
                                JOptionPane.ERROR_MESSAGE
                        );
                    }
                } catch (SQLException e) {
                    // Captura errores de restricción de integridad o base de datos
                    JOptionPane.showMessageDialog(
                            this,
                            "No se puede eliminar la asignación: " + e.getMessage(),
                            "Error de Base de Datos",
                            JOptionPane.WARNING_MESSAGE
                    );
                }   
            }      
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "El ID de la asignación no es válido.");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,
                    "Error inesperado: " + e.getMessage(),
                    "Error",
                    JOptionPane.ERROR_MESSAGE
            );
        }
    }
            
    
    
}
