/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package views;

import controllers.AnimalController;
import controllers.RefugioController;
import enums.EstadoSalud;
import java.sql.SQLException;
import java.time.Year;
import java.util.Date;
import javax.swing.JOptionPane;
import models.Refugio;

/**
 *
 * @author valeria
 */
public class FrmAdminAnimales extends javax.swing.JFrame {

    private AnimalController aController;
    private RefugioController rController;
    private javax.swing.JFrame ventanaPadre;
    
    private int idRefugio;
    
    /**
     * Creates new form FrmAdminAnimales
     */
    public FrmAdminAnimales(javax.swing.JFrame ventanaPadre, int idRefugio) {
        initComponents();
        cargarComboSalud(); // Rellenar el comboBox con enum EstadoSalud
        this.idRefugio=idRefugio; // id del refugio dado por la pantalla anterior
        rController = new RefugioController();
        aController = new AnimalController();
        cargarTablaAnimales(idRefugio);
        
        btnEliminar.setVisible(false);
        this.setLocationRelativeTo(null); // Centra la ventana en la pantalla
        this.setResizable(false);
        this.ventanaPadre = ventanaPadre;
        
        // Convertir el entero a String para salarlo al txt
        int numero = idRefugio;
        String id2 = String.valueOf(numero);
        txtRefugio.setText(id2);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlBase = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        lblSubRefugios = new javax.swing.JLabel();
        lblTituloAdminV = new javax.swing.JLabel();
        lblSubtituloRegistro = new javax.swing.JLabel();
        lblID = new javax.swing.JLabel();
        lblNombre = new javax.swing.JLabel();
        lblFecha = new javax.swing.JLabel();
        lblEspecialidad = new javax.swing.JLabel();
        cmbSalud = new javax.swing.JComboBox<>();
        lblCorreo = new javax.swing.JLabel();
        txtID = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        txtEspecie = new javax.swing.JTextField();
        btnRegistrar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        btnListo = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        scrlTabla = new javax.swing.JScrollPane();
        tblAnimales = new javax.swing.JTable();
        txtFiltro = new javax.swing.JTextField();
        lblSubtituloFiltro = new javax.swing.JLabel();
        lblRefugio = new javax.swing.JLabel();
        txtRefugio = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txtAnio = new javax.swing.JTextField();
        dcFechaIngreso = new com.toedter.calendar.JDateChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnlBase.setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        lblSubRefugios.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        lblSubRefugios.setForeground(new java.awt.Color(102, 102, 102));
        lblSubRefugios.setText("Refugios Cajeme");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(lblSubRefugios)
                .addContainerGap(678, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblSubRefugios)
                .addContainerGap(7, Short.MAX_VALUE))
        );

        lblTituloAdminV.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        lblTituloAdminV.setForeground(new java.awt.Color(102, 102, 102));
        lblTituloAdminV.setText("Administración Animales");

        lblSubtituloRegistro.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        lblSubtituloRegistro.setForeground(new java.awt.Color(102, 102, 102));
        lblSubtituloRegistro.setText("Registrar un Animal");

        lblID.setText("ID:");

        lblNombre.setText("Nombre:");

        lblFecha.setText("Especie:");

        lblEspecialidad.setText("Estado salud:");

        cmbSalud.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        lblCorreo.setText("Fecha Ingreso:");

        txtID.setEditable(false);

        txtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreActionPerformed(evt);
            }
        });

        txtEspecie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEspecieActionPerformed(evt);
            }
        });

        btnRegistrar.setBackground(new java.awt.Color(0, 153, 255));
        btnRegistrar.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        btnRegistrar.setForeground(new java.awt.Color(255, 255, 255));
        btnRegistrar.setText("REGISTRAR");
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });

        btnCancelar.setBackground(new java.awt.Color(0, 153, 255));
        btnCancelar.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        btnCancelar.setForeground(new java.awt.Color(255, 255, 255));
        btnCancelar.setText("CANCELAR");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        btnListo.setBackground(new java.awt.Color(0, 153, 0));
        btnListo.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        btnListo.setForeground(new java.awt.Color(255, 255, 255));
        btnListo.setText("LISTO");
        btnListo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListoActionPerformed(evt);
            }
        });

        btnEliminar.setBackground(new java.awt.Color(0, 153, 255));
        btnEliminar.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        btnEliminar.setForeground(new java.awt.Color(255, 255, 255));
        btnEliminar.setText("ELIMINAR");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        tblAnimales.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tblAnimales.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblAnimalesMouseClicked(evt);
            }
        });
        scrlTabla.setViewportView(tblAnimales);

        txtFiltro.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtFiltroKeyReleased(evt);
            }
        });

        lblSubtituloFiltro.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        lblSubtituloFiltro.setForeground(new java.awt.Color(102, 102, 102));
        lblSubtituloFiltro.setText("------- Filtrar por Nombre -------");

        lblRefugio.setText("Refugio:");

        txtRefugio.setEditable(false);

        jLabel1.setText("Año nacimiento:");

        dcFechaIngreso.setDateFormatString("dd/MM/yyyy");
        dcFechaIngreso.setMaxSelectableDate(new java.util.Date(4102473600000L));
        dcFechaIngreso.setMinSelectableDate(new java.util.Date(-631123200000L));

        javax.swing.GroupLayout pnlBaseLayout = new javax.swing.GroupLayout(pnlBase);
        pnlBase.setLayout(pnlBaseLayout);
        pnlBaseLayout.setHorizontalGroup(
            pnlBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlBaseLayout.createSequentialGroup()
                .addGap(137, 137, 137)
                .addGroup(pnlBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlBaseLayout.createSequentialGroup()
                        .addComponent(lblTituloAdminV)
                        .addGap(274, 274, 274))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlBaseLayout.createSequentialGroup()
                        .addComponent(btnRegistrar)
                        .addGap(33, 33, 33)
                        .addComponent(btnCancelar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnEliminar)
                        .addGap(189, 189, 189))))
            .addGroup(pnlBaseLayout.createSequentialGroup()
                .addGroup(pnlBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlBaseLayout.createSequentialGroup()
                        .addGroup(pnlBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(pnlBaseLayout.createSequentialGroup()
                                    .addGap(37, 37, 37)
                                    .addGroup(pnlBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(lblFecha)
                                        .addComponent(lblNombre)
                                        .addComponent(lblEspecialidad)))
                                .addGroup(pnlBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(pnlBaseLayout.createSequentialGroup()
                                        .addGap(124, 124, 124)
                                        .addGroup(pnlBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txtNombre)
                                            .addComponent(cmbSalud, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtEspecie, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlBaseLayout.createSequentialGroup()
                                        .addComponent(lblCorreo)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(dcFechaIngreso, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(pnlBaseLayout.createSequentialGroup()
                                .addGap(25, 25, 25)
                                .addGroup(pnlBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(pnlBaseLayout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtAnio, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(pnlBaseLayout.createSequentialGroup()
                                        .addGroup(pnlBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblID)
                                            .addGroup(pnlBaseLayout.createSequentialGroup()
                                                .addGap(22, 22, 22)
                                                .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(116, 116, 116)))))
                        .addGap(36, 36, 36))
                    .addGroup(pnlBaseLayout.createSequentialGroup()
                        .addGroup(pnlBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlBaseLayout.createSequentialGroup()
                                .addGap(180, 180, 180)
                                .addComponent(lblSubtituloRegistro))
                            .addGroup(pnlBaseLayout.createSequentialGroup()
                                .addGap(72, 72, 72)
                                .addComponent(lblRefugio)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtRefugio, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(68, 68, 68)))
                .addGroup(pnlBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlBaseLayout.createSequentialGroup()
                        .addComponent(txtFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(101, 101, 101))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlBaseLayout.createSequentialGroup()
                        .addComponent(lblSubtituloFiltro)
                        .addGap(130, 130, 130))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlBaseLayout.createSequentialGroup()
                        .addComponent(scrlTabla, javax.swing.GroupLayout.PREFERRED_SIZE, 403, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlBaseLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnListo)
                .addGap(16, 16, 16))
        );
        pnlBaseLayout.setVerticalGroup(
            pnlBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBaseLayout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblTituloAdminV)
                .addGap(43, 43, 43)
                .addGroup(pnlBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnlBaseLayout.createSequentialGroup()
                        .addComponent(lblSubtituloFiltro)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(scrlTabla, javax.swing.GroupLayout.DEFAULT_SIZE, 184, Short.MAX_VALUE)
                        .addGap(64, 64, 64))
                    .addGroup(pnlBaseLayout.createSequentialGroup()
                        .addComponent(lblSubtituloRegistro)
                        .addGap(26, 26, 26)
                        .addGroup(pnlBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblID)
                            .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(8, 8, 8)
                        .addGroup(pnlBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlBaseLayout.createSequentialGroup()
                                .addGroup(pnlBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblNombre)
                                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtEspecie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnlBaseLayout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addComponent(lblFecha)
                                .addGap(12, 12, 12)
                                .addGroup(pnlBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblEspecialidad)
                                    .addComponent(cmbSalud, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txtAnio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblCorreo)
                            .addComponent(dcFechaIngreso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblRefugio)
                            .addComponent(txtRefugio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(55, 55, 55)))
                .addGroup(pnlBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRegistrar)
                    .addComponent(btnCancelar)
                    .addComponent(btnEliminar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnListo)
                .addGap(17, 17, 17))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlBase, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlBase, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreActionPerformed

    private void txtEspecieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEspecieActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEspecieActionPerformed

    private void txtFiltroKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFiltroKeyReleased
        buscar();
    }//GEN-LAST:event_txtFiltroKeyReleased

    private void btnListoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListoActionPerformed
        // 1. Cerramos el registro (se libera esta memoria)
        this.dispose(); 

        // 2. Usamos la referencia que guardamos para mostrar la original
        if (ventanaPadre != null) {
            ventanaPadre.setVisible(true);
        }
    }//GEN-LAST:event_btnListoActionPerformed

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
        guardarAnimal();
    }//GEN-LAST:event_btnRegistrarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        limpiarFormulario();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        eliminarAnimal();
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void tblAnimalesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblAnimalesMouseClicked
        cargarDatosATxt();
    }//GEN-LAST:event_tblAnimalesMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnListo;
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JComboBox<Object> cmbSalud;
    private com.toedter.calendar.JDateChooser dcFechaIngreso;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblCorreo;
    private javax.swing.JLabel lblEspecialidad;
    private javax.swing.JLabel lblFecha;
    private javax.swing.JLabel lblID;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblRefugio;
    private javax.swing.JLabel lblSubRefugios;
    private javax.swing.JLabel lblSubtituloFiltro;
    private javax.swing.JLabel lblSubtituloRegistro;
    private javax.swing.JLabel lblTituloAdminV;
    private javax.swing.JPanel pnlBase;
    private javax.swing.JScrollPane scrlTabla;
    private javax.swing.JTable tblAnimales;
    private javax.swing.JTextField txtAnio;
    private javax.swing.JTextField txtEspecie;
    private javax.swing.JTextField txtFiltro;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtRefugio;
    // End of variables declaration//GEN-END:variables

    private void cargarComboSalud() {
       cmbSalud.removeAllItems();

        // 2. Agregamos el String de instrucción (será el índice 0)
        cmbSalud.addItem("Seleccione una opcion");

        // 3. Agregamos los objetos reales del Enum
        for (EstadoSalud e : EstadoSalud.values()) {
            cmbSalud.addItem(e); 
        }
        
    }

    private void cargarTablaAnimales(int idRefugio) {
        tblAnimales.setModel(aController.obtenerTablaAnimales(idRefugio));
    }
    
    private void guardarAnimal(){
    try {
            // 1. Ejecutar validación completa
            if (!validarCampos()) {
                return; 
            }

            // Tomar datos de texto y números
            String nombre = txtNombre.getText().trim();
            String especie = txtEspecie.getText().trim();

            // Manejo del ID del Refugio (Conversión de String a int como vimos antes)
            int idRefugio = Integer.parseInt(txtRefugio.getText().trim());

            // Manejo del Enum EstadoSalud
            Object seleccionado = cmbSalud.getSelectedItem();
            if (seleccionado instanceof String) {
                JOptionPane.showMessageDialog(this, "Por favor seleccione un estado de salud válido.");
                return;
            }
            EstadoSalud estado = (EstadoSalud) seleccionado;

            // Manejo de Year (anioNac) - Asumiendo un campo de texto o JYearChooser
            // Convertimos el String del año a la clase java.time.Year
            Year anioNac = Year.parse(txtAnio.getText().trim());

            // Manejo de la Fecha de Ingreso (Date a sql.Date)
            Date fechaIng = dcFechaIngreso.getDate();
            java.sql.Date sqlFechaIng = new java.sql.Date(fechaIng.getTime());

            // --- Lógica de PERSISTENCIA ---

            // 3. Lógica para GUARDAR (Insertar)
            if (btnRegistrar.getText().equals("REGISTRAR")) {
                boolean exito = aController.agregarAnimal(nombre, especie, estado, anioNac, sqlFechaIng, idRefugio);
                if (exito) {
                    JOptionPane.showMessageDialog(this, "Animal registrado con éxito");
                    cargarTablaAnimales(idRefugio); 
                } else {
                    JOptionPane.showMessageDialog(this, "Error al guardar el animal", "Error", JOptionPane.ERROR_MESSAGE);
                }
            } 

            // 4. Lógica para ACTUALIZAR
            else if (btnRegistrar.getText().equals("ACTUALIZAR")) {
                int id = Integer.parseInt(txtID.getText().trim()); 
                boolean exito = aController.editarAnimal(id, nombre, especie, estado, anioNac, sqlFechaIng, idRefugio);
                if (exito) {
                    JOptionPane.showMessageDialog(this, "Datos del animal actualizados.");
                    cargarTablaAnimales(idRefugio);
                } else {
                    JOptionPane.showMessageDialog(this, "Error al actualizar.", "Error", JOptionPane.ERROR_MESSAGE);
                }
            }

            limpiarFormulario(); 
        }catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "El ID de refugio o el Año deben ser numéricos.", "Error", JOptionPane.ERROR_MESSAGE);
        } catch (java.time.format.DateTimeParseException ex) {
            JOptionPane.showMessageDialog(this, "Año no válido (Use AAAA).", "Error", JOptionPane.ERROR_MESSAGE);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Error: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    private boolean validarCampos() {
        // Validar que no estén vacíos
        if (txtNombre.getText().trim().isEmpty() || txtEspecie.getText().trim().isEmpty() || 
            txtRefugio.getText().trim().isEmpty() || dcFechaIngreso.getDate() == null || txtAnio.getText().trim().isEmpty() || cmbSalud.getSelectedIndex() == 0) {
            JOptionPane.showMessageDialog(this, "Todos los campos son obligatorios.");
            return false;
        }
        
        // Validar Nombre (Solo letras y espacios)
        if (!txtNombre.getText().matches("^[a-zA-ZáéíóúÁÉÍÓÚñÑ ]+$")) {
            JOptionPane.showMessageDialog(this, "El nombre solo debe contener letras.");
            return false;
        }
        
        // Validar Nombre (Solo letras y espacios)
        if (!txtEspecie.getText().matches("^[a-zA-ZáéíóúÁÉÍÓÚñÑ ]+$")) {
            JOptionPane.showMessageDialog(this, "La especie solo debe contener letras.");
            return false;
        }
        
        // Validar ComboBox (Que no esté en el índice 0 si es un mensaje de "Seleccione...")
        if (cmbSalud.getSelectedIndex() == 0) { 
            JOptionPane.showMessageDialog(this, "Debe seleccionar un estado de salud.");
            return false;
        }
        
        // Validar Nombre (Solo letras y espacios)
        if (!txtNombre.getText().matches("^[a-zA-ZáéíóúÁÉÍÓÚñÑ ]+$")) {
            JOptionPane.showMessageDialog(this, "El nombre solo debe contener letras.");
            return false;
        }
        

        // 2. Validar que sean exactamente 4 dígitos numéricos
        if (!txtAnio.getText().matches("\\d{4}")) {
            JOptionPane.showMessageDialog(this, "El año debe tener 4 dígitos (ejemplo: 2005).");
            return false;
        }

        // 3. Validar que no sea un año ilógico (ejemplo: mayor al año actual)
        int anioInt = Integer.parseInt(txtAnio.getText().trim());
        int anioActual = java.time.Year.now().getValue();

        if (anioInt < 1900 || anioInt > anioActual) {
            JOptionPane.showMessageDialog(this, "Ingrese un año válido entre 1900 y " + anioActual);
            return false;
        }
        
        // Validar Fecha de Nacimiento (Razonable: que no sea hoy ni en el futuro)
        java.util.Date fechaSeleccionada = dcFechaIngreso.getDate();
        java.util.Date hoy = new java.util.Date();
        if (fechaSeleccionada.after(hoy)) {
            JOptionPane.showMessageDialog(this, "La fecha de ingreso no puede ser futura.");
            return false;
        }
        
        int idRefugio = Integer.parseInt(txtRefugio.getText().trim());

        Refugio r = rController.obtenerRefugio(idRefugio);

        if (r == null) {
            JOptionPane.showMessageDialog(this, "El ID de Refugio " + idRefugio + " no existe en la base de datos.", "Refugio no encontrado", JOptionPane.WARNING_MESSAGE);
            return false; // Detiene el proceso de guardado
        }
        return true;
    }

    private void limpiarFormulario() {
        txtID.setText("");
        txtNombre.setText("");
        txtEspecie.setText("");
        cmbSalud.setSelectedIndex(0);
        txtAnio.setText("");
        dcFechaIngreso.setDate(null);
        txtRefugio.setText("");
        
        btnRegistrar.setText("REGISTRAR");
        btnEliminar.setVisible(false);
    }
    
    private void cargarDatosATxt(){
        int fila = tblAnimales.getSelectedRow();
        if(fila>=0){
            txtID.setText(tblAnimales.getValueAt(fila, 0).toString());
            txtNombre.setText(tblAnimales.getValueAt(fila, 1).toString());
            txtEspecie.setText(tblAnimales.getValueAt(fila, 2).toString());
            cmbSalud.setSelectedItem(tblAnimales.getValueAt(fila, 3));
            txtAnio.setText(tblAnimales.getValueAt(fila, 4).toString());
            dcFechaIngreso.setDate((java.util.Date) tblAnimales.getValueAt(fila, 5));
            txtRefugio.setText(tblAnimales.getValueAt(fila, 6).toString());
            
            btnRegistrar.setText("ACTUALIZAR");
            btnEliminar.setVisible(true);
            
        }
    }
    
    private void buscar(){
        String nombre = txtFiltro.getText().trim();
        if(nombre.isEmpty()){
            cargarTablaAnimales(idRefugio);
        } else {
            tblAnimales.setModel(aController.obtenerTablaAnimalesFiltradoNombre(nombre, idRefugio));
        }
    }
    
    private void eliminarAnimal() {
        try {
            int id = Integer.parseInt(txtID.getText());

            int confirm = JOptionPane.showConfirmDialog(this, 
                    "Esta seguro de querer eliminar al animal?",
                    "Confirmacion eliminacion", 
                    JOptionPane.YES_NO_OPTION);

            if(confirm == JOptionPane.YES_OPTION){
                
                try{
                    boolean exito = aController.eliminarAnimal(id);
                    if(exito){
                        JOptionPane.showMessageDialog(this, "Animal eliminado con exito");
                        cargarTablaAnimales(idRefugio);
                        limpiarFormulario();
                    }else{
                        JOptionPane.showMessageDialog(
                                this,
                                "No se encontro al animal a eliminar",
                                "Error",
                                JOptionPane.ERROR_MESSAGE
                        );
                    }
                } catch (SQLException e){
                    JOptionPane.showMessageDialog(
                            this,
                            e.getMessage(), // Aquí saldrá: "No se puede eliminar el voluntario porque..."
                            "Restricción de Base de Datos",
                            JOptionPane.WARNING_MESSAGE
                    );
                }   
            }      
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,
                    "Error: "+e.getMessage(),
                    "Error",
                    JOptionPane.ERROR_MESSAGE
            );
        }
    }
    
    
    
}
