/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package views;

import controllers.RefugioController;
import controllers.VoluntarioController;
import enums.Especialidad;
import java.sql.SQLException;
import java.time.LocalDate;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author valeria
 */
public class FrmAdminVoluntarios extends javax.swing.JFrame {

    RefugioController rController;
    VoluntarioController vController;
    
    private javax.swing.JFrame ventanaPadre;
    private int id;
    /**
     * Creates new form FrmAdminVoluntarios
     */
    public FrmAdminVoluntarios(javax.swing.JFrame ventanaPadre, int id) {
        initComponents();
        cargarComboEstados();
        this.id=id;
        rController = new RefugioController();
        vController = new VoluntarioController();
        
        
        cargarTablaVoluntarios();

        
        btnEliminar.setVisible(false);
        this.setLocationRelativeTo(null); // Centra la ventana en la pantalla
        this.setResizable(false);
        this.ventanaPadre = ventanaPadre;
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlBase = new javax.swing.JPanel();
        pnlSub = new javax.swing.JPanel();
        lblTituloSuperior = new javax.swing.JLabel();
        lblTituloAdminV = new javax.swing.JLabel();
        lblSubtituloRegistro = new javax.swing.JLabel();
        lblID = new javax.swing.JLabel();
        lblNombre = new javax.swing.JLabel();
        lblFecha = new javax.swing.JLabel();
        lblEspecialidad = new javax.swing.JLabel();
        lblCorreo = new javax.swing.JLabel();
        lblTelefono = new javax.swing.JLabel();
        txtID = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        txtCorreo = new javax.swing.JTextField();
        txtTelefono = new javax.swing.JTextField();
        dcFechaNacimiento = new com.toedter.calendar.JDateChooser();
        cmbEspecialidad = new javax.swing.JComboBox<>();
        lblSubtituloFiltro = new javax.swing.JLabel();
        scrlTabla = new javax.swing.JScrollPane();
        tblVoluntarios = new javax.swing.JTable();
        txtFiltro = new javax.swing.JTextField();
        btnRegistrar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnListo = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnlBase.setBackground(new java.awt.Color(255, 255, 255));
        pnlBase.setEnabled(false);

        pnlSub.setBackground(new java.awt.Color(204, 204, 204));

        lblTituloSuperior.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        lblTituloSuperior.setForeground(new java.awt.Color(102, 102, 102));
        lblTituloSuperior.setText("Refugios Cajeme");

        javax.swing.GroupLayout pnlSubLayout = new javax.swing.GroupLayout(pnlSub);
        pnlSub.setLayout(pnlSubLayout);
        pnlSubLayout.setHorizontalGroup(
            pnlSubLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSubLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(lblTituloSuperior)
                .addContainerGap(677, Short.MAX_VALUE))
        );
        pnlSubLayout.setVerticalGroup(
            pnlSubLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSubLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTituloSuperior)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        lblTituloAdminV.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        lblTituloAdminV.setForeground(new java.awt.Color(102, 102, 102));
        lblTituloAdminV.setText("Administración Voluntarios");

        lblSubtituloRegistro.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        lblSubtituloRegistro.setForeground(new java.awt.Color(102, 102, 102));
        lblSubtituloRegistro.setText("Registrar un Voluntario");

        lblID.setText("ID:");

        lblNombre.setText("Nombre:");

        lblFecha.setText("Fecha de nacimiento:");

        lblEspecialidad.setText("Especialidad:");

        lblCorreo.setText("Correo:");

        lblTelefono.setText("Telefono:");

        txtID.setEditable(false);

        txtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreActionPerformed(evt);
            }
        });

        dcFechaNacimiento.setDateFormatString("dd/MM/yyyy");
        dcFechaNacimiento.setMaxSelectableDate(new java.util.Date(4102473600000L));
        dcFechaNacimiento.setMinSelectableDate(new java.util.Date(-2208958568000L));

        cmbEspecialidad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        lblSubtituloFiltro.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        lblSubtituloFiltro.setForeground(new java.awt.Color(102, 102, 102));
        lblSubtituloFiltro.setText("------- Filtrar por Nombre -------");

        tblVoluntarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tblVoluntarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblVoluntariosMouseClicked(evt);
            }
        });
        scrlTabla.setViewportView(tblVoluntarios);

        txtFiltro.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtFiltroKeyReleased(evt);
            }
        });

        btnRegistrar.setBackground(new java.awt.Color(255, 102, 0));
        btnRegistrar.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        btnRegistrar.setForeground(new java.awt.Color(255, 255, 255));
        btnRegistrar.setText("REGISTRAR");
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });

        btnCancelar.setBackground(new java.awt.Color(255, 102, 0));
        btnCancelar.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        btnCancelar.setForeground(new java.awt.Color(255, 255, 255));
        btnCancelar.setText("CANCELAR");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        btnEliminar.setBackground(new java.awt.Color(255, 102, 0));
        btnEliminar.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        btnEliminar.setForeground(new java.awt.Color(255, 255, 255));
        btnEliminar.setText("ELIMINAR");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        btnListo.setBackground(new java.awt.Color(0, 204, 0));
        btnListo.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        btnListo.setForeground(new java.awt.Color(255, 255, 255));
        btnListo.setText("LISTO");
        btnListo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlBaseLayout = new javax.swing.GroupLayout(pnlBase);
        pnlBase.setLayout(pnlBaseLayout);
        pnlBaseLayout.setHorizontalGroup(
            pnlBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlSub, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pnlBaseLayout.createSequentialGroup()
                .addGap(154, 154, 154)
                .addComponent(lblSubtituloRegistro)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblSubtituloFiltro)
                .addGap(112, 112, 112))
            .addGroup(pnlBaseLayout.createSequentialGroup()
                .addGap(277, 277, 277)
                .addComponent(lblTituloAdminV)
                .addContainerGap(290, Short.MAX_VALUE))
            .addGroup(pnlBaseLayout.createSequentialGroup()
                .addGap(125, 125, 125)
                .addComponent(btnRegistrar)
                .addGap(51, 51, 51)
                .addComponent(btnCancelar)
                .addGap(163, 163, 163)
                .addComponent(btnEliminar)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlBaseLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnListo)
                .addGap(14, 14, 14))
            .addGroup(pnlBaseLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(pnlBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblFecha)
                    .addComponent(lblNombre)
                    .addComponent(lblID)
                    .addComponent(lblEspecialidad)
                    .addComponent(lblCorreo)
                    .addComponent(lblTelefono))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtTelefono)
                    .addComponent(txtNombre)
                    .addComponent(dcFechaNacimiento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtCorreo, javax.swing.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE)
                    .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbEspecialidad, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlBaseLayout.createSequentialGroup()
                        .addComponent(txtFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(86, 86, 86))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlBaseLayout.createSequentialGroup()
                        .addComponent(scrlTabla, javax.swing.GroupLayout.PREFERRED_SIZE, 349, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32))))
        );
        pnlBaseLayout.setVerticalGroup(
            pnlBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBaseLayout.createSequentialGroup()
                .addComponent(pnlSub, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblTituloAdminV)
                .addGap(34, 34, 34)
                .addGroup(pnlBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSubtituloRegistro)
                    .addComponent(lblSubtituloFiltro))
                .addGap(18, 18, 18)
                .addGroup(pnlBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlBaseLayout.createSequentialGroup()
                        .addComponent(txtFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(16, 16, 16)
                        .addComponent(scrlTabla, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlBaseLayout.createSequentialGroup()
                        .addGroup(pnlBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblID)
                            .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblNombre)
                            .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblFecha)
                            .addComponent(dcFechaNacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblEspecialidad)
                            .addComponent(cmbEspecialidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblCorreo)
                            .addComponent(txtCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblTelefono)
                            .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addGroup(pnlBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRegistrar)
                    .addComponent(btnCancelar)
                    .addComponent(btnEliminar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnListo)
                .addGap(14, 14, 14))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlBase, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlBase, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        limpiarFormulario();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        eliminarVoluntario();
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
        guardarVoluntario();
    }//GEN-LAST:event_btnRegistrarActionPerformed

    private void txtFiltroKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFiltroKeyReleased
        buscar();
    }//GEN-LAST:event_txtFiltroKeyReleased

    private void tblVoluntariosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblVoluntariosMouseClicked
        cargarDatosATxt();
    }//GEN-LAST:event_tblVoluntariosMouseClicked

    private void btnListoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListoActionPerformed
        // 1. Cerramos el registro (se libera esta memoria)
        this.dispose(); 

        // 2. Usamos la referencia que guardamos para mostrar la original
        if (ventanaPadre != null) {
            ventanaPadre.setVisible(true);
        }
    }//GEN-LAST:event_btnListoActionPerformed

    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnListo;
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JComboBox<Object> cmbEspecialidad;
    private com.toedter.calendar.JDateChooser dcFechaNacimiento;
    private javax.swing.JLabel lblCorreo;
    private javax.swing.JLabel lblEspecialidad;
    private javax.swing.JLabel lblFecha;
    private javax.swing.JLabel lblID;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblSubtituloFiltro;
    private javax.swing.JLabel lblSubtituloRegistro;
    private javax.swing.JLabel lblTelefono;
    private javax.swing.JLabel lblTituloAdminV;
    private javax.swing.JLabel lblTituloSuperior;
    private javax.swing.JPanel pnlBase;
    private javax.swing.JPanel pnlSub;
    private javax.swing.JScrollPane scrlTabla;
    private javax.swing.JTable tblVoluntarios;
    private javax.swing.JTextField txtCorreo;
    private javax.swing.JTextField txtFiltro;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtTelefono;
    // End of variables declaration//GEN-END:variables

    private void cargarComboEstados() {
       
        cmbEspecialidad.removeAllItems();

        // 2. Agregamos el String de instrucción (será el índice 0)
        cmbEspecialidad.addItem("Seleccione una opcion");

        // 3. Agregamos los objetos reales del Enum
        for (Especialidad e : Especialidad.values()) {
            cmbEspecialidad.addItem(e); 
        }
    }

    private void cargarTablaVoluntarios() {
        tblVoluntarios.setModel(vController.obtenerTablaVoluntarios());
    }

    private void guardarVoluntario(){
        try {
            // 2. Ejecutar validación completa
            if (!validarCampos()) {
                return; 
            }
            
            // Tomar datos de los campos
            String nombre = txtNombre.getText().trim();
            String correo = txtCorreo.getText().trim();
            String telefono = txtTelefono.getText().trim();

            
           // 1. Obtenemos el objeto directamente
            Object seleccionado = cmbEspecialidad.getSelectedItem();

            // 2. Validamos que no sea el String de "Seleccione una opcion"
            if (seleccionado instanceof String) {
                JOptionPane.showMessageDialog(this, "Por favor seleccione una especialidad válida.");
                return;
            }

            // 3. Como ya sabemos que no es el String, lo casteamos directo a Especialidad
            Especialidad especialidad = (Especialidad) seleccionado;

            Date fechaNac = dcFechaNacimiento.getDate();
            java.sql.Date sqlFechaNac = new java.sql.Date(fechaNac.getTime());


            
            // 2. Ejecutar validación completa
            if (!validarCampos()) {
                return; 
            }

            // 3. Lógica para GUARDAR (Insertar)
            if (btnRegistrar.getText().equals("REGISTRAR")) {
                boolean exito = vController.agregarVoluntario(nombre, sqlFechaNac, especialidad, correo, telefono);
                if (exito) {
                    JOptionPane.showMessageDialog(this, "Voluntario registrado con éxito");
                    cargarTablaVoluntarios(); 
                } else {
                    JOptionPane.showMessageDialog(this, "Error al guardar el voluntario", "Error", JOptionPane.ERROR_MESSAGE);
                }
            } 

            // 4. Lógica para ACTUALIZAR
            else if (btnRegistrar.getText().equals("ACTUALIZAR")) {
                int id = Integer.parseInt(txtID.getText().trim()); 

                boolean exito = vController.editarVoluntario(id, nombre, sqlFechaNac, especialidad, correo, telefono);
                if (exito) {
                    JOptionPane.showMessageDialog(this, "Datos del voluntario actualizados.");
                    cargarTablaVoluntarios();
                } else {
                    JOptionPane.showMessageDialog(this, "Error al actualizar.", "Error", JOptionPane.ERROR_MESSAGE);
                }
            }

            limpiarFormulario(); 

        } catch (java.time.format.DateTimeParseException ex) {
            JOptionPane.showMessageDialog(this, "Formato de fecha incorrecto (Use AAAA-MM-DD)", "Error", JOptionPane.ERROR_MESSAGE);
            
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Error: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    private boolean validarCampos() {
        // Validar que no estén vacíos
        if (txtNombre.getText().isEmpty() || txtCorreo.getText().isEmpty() || 
            txtTelefono.getText().isEmpty() || dcFechaNacimiento.getDate() == null) {
            JOptionPane.showMessageDialog(this, "Todos los campos son obligatorios.");
            return false;
        }

        // Validar Nombre (Solo letras y espacios)
        if (!txtNombre.getText().matches("^[a-zA-ZáéíóúÁÉÍÓÚñÑ ]+$")) {
            JOptionPane.showMessageDialog(this, "El nombre solo debe contener letras.");
            return false;
        }

        // Validar Fecha de Nacimiento (Razonable: que no sea hoy ni en el futuro)
        java.util.Date fechaSeleccionada = dcFechaNacimiento.getDate();
        java.util.Date hoy = new java.util.Date();
        if (fechaSeleccionada.after(hoy)) {
            JOptionPane.showMessageDialog(this, "La fecha de nacimiento no puede ser futura.");
            return false;
        }

        // Validar ComboBox (Que no esté en el índice 0 si es un mensaje de "Seleccione...")
        if (cmbEspecialidad.getSelectedIndex() == 0) { 
            JOptionPane.showMessageDialog(this, "Debe seleccionar una especialidad.");
            return false;
        }

        // 5. Validar Correo Electrónico (Formato estándar)
        String regexCorreo = "^[A-Za-z0-9+_.-]+@[A-Za-z0-9.-]+\\.[A-Za-z]{2,}$";
        if (!txtCorreo.getText().matches(regexCorreo)) {
            JOptionPane.showMessageDialog(this, 
                "Formato de correo inválido.\nEjemplo correcto: nombre@dominio.com", 
                "Error de Validación", 
                JOptionPane.WARNING_MESSAGE);
            txtCorreo.requestFocus();
            return false;
        }

        // 6. Validar Teléfono (Solo números, longitud de 7 a 15 dígitos)
        if (!txtTelefono.getText().matches("\\d{7,15}")) {
            JOptionPane.showMessageDialog(this, "El teléfono debe contener solo números (7-15 dígitos).");
            return false;
        }

        return true; // Si pasó todas las pruebas
    }

    private void limpiarFormulario() {
        txtID.setText("");
        txtNombre.setText("");
        dcFechaNacimiento.setDate(null);
        cmbEspecialidad.setSelectedIndex(0);
        txtCorreo.setText("");
        txtTelefono.setText("");
        btnRegistrar.setText("REGISTRAR");
        btnEliminar.setVisible(false);
    }
    
    private void cargarDatosATxt(){
        int fila = tblVoluntarios.getSelectedRow();
        if(fila>=0){
            txtID.setText(tblVoluntarios.getValueAt(fila, 0).toString());
            txtNombre.setText(tblVoluntarios.getValueAt(fila, 1).toString());
            dcFechaNacimiento.setDate((java.util.Date) tblVoluntarios.getValueAt(fila, 2));
            cmbEspecialidad.setSelectedItem(tblVoluntarios.getValueAt(fila, 3));
            txtCorreo.setText(tblVoluntarios.getValueAt(fila, 4).toString());
            txtTelefono.setText(tblVoluntarios.getValueAt(fila, 5).toString());

            btnRegistrar.setText("ACTUALIZAR");
            btnEliminar.setVisible(true);
            
        }
    }
    
    private void buscar(){
        String nombre = txtFiltro.getText().trim();
        if(nombre.isEmpty()){
            cargarTablaVoluntarios();
        } else {
            tblVoluntarios.setModel(vController.obtenerTablaVoluntarioFiltroNombre(nombre));
        }
    }

    private void eliminarVoluntario() {
        try {
            int id = Integer.parseInt(txtID.getText());

            int confirm = JOptionPane.showConfirmDialog(this, 
                    "Esta seguro de querer eliminar al voluntario?",
                    "Confirmacion eliminacion", 
                    JOptionPane.YES_NO_OPTION);

            if(confirm == JOptionPane.YES_OPTION){
                
                try{
                    boolean exito = vController.eliminarVoluntario(id);
                    if(exito){
                        JOptionPane.showMessageDialog(this, "Cliente eliminado con exito");
                        cargarTablaVoluntarios();
                        limpiarFormulario();
                    }else{
                        JOptionPane.showMessageDialog(
                                this,
                                "No se encontro al voluntario a eliminar",
                                "Error",
                                JOptionPane.ERROR_MESSAGE
                        );
                    }
                } catch (SQLException e){
                    JOptionPane.showMessageDialog(
                            this,
                            e.getMessage(), // Aquí saldrá: "No se puede eliminar el voluntario porque..."
                            "Restricción de Base de Datos",
                            JOptionPane.WARNING_MESSAGE
                    );
                }   
            }      
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,
                    "Error: "+e.getMessage(),
                    "Error",
                    JOptionPane.ERROR_MESSAGE
            );
        }
    }
    
    
    
}
