/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package views;

import controllers.RefugioController;
import java.awt.Component;

/**
 *
 * @author valeria
 */
public class FrmRefugioPrincipal extends javax.swing.JFrame {
    
    RefugioController rController;
    private javax.swing.JFrame ventanaPadre;
    
    private int idRefugio;
    private String nombre;
    private String ubicacion;

    // Constructor modificado
    public FrmRefugioPrincipal(javax.swing.JFrame padre, int idRefugio, String nombre, String ubi) {
        initComponents();
        this.ventanaPadre = padre;
        rController = new RefugioController();
        this.setLocationRelativeTo(null); // Centra la ventana en la pantalla
        this.setResizable(false);
        
        this.idRefugio = idRefugio;
        this.nombre = nombre;
        this.ubicacion = ubi;
        
        // Ejemplo: Poner el nombre del refugio en el título de la ventana
        this.setTitle("Acceso a Refugio: " + nombre);
        
        lblNombreRefugio.setText(nombre);
        lblUbi.setText(ubi);
    }

    /**
     * Creates new form FrmRefugioPrincipal
     */
    public FrmRefugioPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlBase = new javax.swing.JPanel();
        lblNombreRefugio = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblUbi = new javax.swing.JLabel();
        lblRefugio = new javax.swing.JLabel();
        btnSalir = new javax.swing.JButton();
        menuBar = new javax.swing.JMenuBar();
        menuVoluntarios = new javax.swing.JMenu();
        menuItemAdmVoluntarios = new javax.swing.JMenuItem();
        menuItemListaVoluntarios = new javax.swing.JMenuItem();
        menuAnimales = new javax.swing.JMenu();
        menuItemAdmAnimales = new javax.swing.JMenuItem();
        menuItemListaAnimales = new javax.swing.JMenuItem();
        menuAsignaciones = new javax.swing.JMenu();
        menuItemAdmAsignaciones = new javax.swing.JMenuItem();
        menuItemListaAsignaciones = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnlBase.setBackground(new java.awt.Color(255, 255, 255));

        lblNombreRefugio.setFont(new java.awt.Font("InaiMathi", 1, 30)); // NOI18N
        lblNombreRefugio.setForeground(new java.awt.Color(102, 102, 102));
        lblNombreRefugio.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNombreRefugio.setText("-- Nombre Refugio --");

        jLabel2.setText("Refugio ubicado en: ");

        lblUbi.setText("-- UBICACION REFUGIO --");

        lblRefugio.setFont(new java.awt.Font("InaiMathi", 1, 30)); // NOI18N
        lblRefugio.setForeground(new java.awt.Color(153, 153, 153));
        lblRefugio.setText("Refugio");

        btnSalir.setText("SALIR");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlBaseLayout = new javax.swing.GroupLayout(pnlBase);
        pnlBase.setLayout(pnlBaseLayout);
        pnlBaseLayout.setHorizontalGroup(
            pnlBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBaseLayout.createSequentialGroup()
                .addGroup(pnlBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlBaseLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnSalir))
                    .addGroup(pnlBaseLayout.createSequentialGroup()
                        .addGroup(pnlBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlBaseLayout.createSequentialGroup()
                                .addGap(342, 342, 342)
                                .addComponent(lblRefugio))
                            .addGroup(pnlBaseLayout.createSequentialGroup()
                                .addGap(260, 260, 260)
                                .addComponent(lblNombreRefugio))
                            .addGroup(pnlBaseLayout.createSequentialGroup()
                                .addGap(245, 245, 245)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblUbi)))
                        .addGap(0, 239, Short.MAX_VALUE)))
                .addContainerGap())
        );
        pnlBaseLayout.setVerticalGroup(
            pnlBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBaseLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(lblRefugio)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblNombreRefugio, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(pnlBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(lblUbi))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 206, Short.MAX_VALUE)
                .addComponent(btnSalir)
                .addContainerGap())
        );

        menuBar.setBackground(new java.awt.Color(204, 204, 204));
        menuBar.setBorder(null);
        menuBar.setForeground(new java.awt.Color(255, 255, 255));
        menuBar.setBorderPainted(false);

        menuVoluntarios.setForeground(new java.awt.Color(153, 153, 153));
        menuVoluntarios.setText("Vountarios");
        menuVoluntarios.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N

        menuItemAdmVoluntarios.setText("Administracion Voluntarios");
        menuItemAdmVoluntarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemAdmVoluntariosActionPerformed(evt);
            }
        });
        menuVoluntarios.add(menuItemAdmVoluntarios);

        menuItemListaVoluntarios.setText("Lista Voluntarios");
        menuItemListaVoluntarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemListaVoluntariosActionPerformed(evt);
            }
        });
        menuVoluntarios.add(menuItemListaVoluntarios);

        menuBar.add(menuVoluntarios);

        menuAnimales.setForeground(new java.awt.Color(153, 153, 153));
        menuAnimales.setText("Animales");
        menuAnimales.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N

        menuItemAdmAnimales.setText("Administracion Animales");
        menuItemAdmAnimales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemAdmAnimalesActionPerformed(evt);
            }
        });
        menuAnimales.add(menuItemAdmAnimales);

        menuItemListaAnimales.setText("Lista Animales");
        menuItemListaAnimales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemListaAnimalesActionPerformed(evt);
            }
        });
        menuAnimales.add(menuItemListaAnimales);

        menuBar.add(menuAnimales);

        menuAsignaciones.setForeground(new java.awt.Color(153, 153, 153));
        menuAsignaciones.setText("Asignaciones");
        menuAsignaciones.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N

        menuItemAdmAsignaciones.setText("Administracion Asignaciones");
        menuItemAdmAsignaciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemAdmAsignacionesActionPerformed(evt);
            }
        });
        menuAsignaciones.add(menuItemAdmAsignaciones);

        menuItemListaAsignaciones.setText("Lista Asignaciones");
        menuItemListaAsignaciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemListaAsignacionesActionPerformed(evt);
            }
        });
        menuAsignaciones.add(menuItemListaAsignaciones);

        menuBar.add(menuAsignaciones);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlBase, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlBase, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuItemAdmAnimalesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemAdmAnimalesActionPerformed
        FrmAdminAnimales adm = new FrmAdminAnimales(this,idRefugio);
        adm.setLocationRelativeTo(null);
        adm.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_menuItemAdmAnimalesActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        // 1. Cerramos el registro (se libera esta memoria)
        this.dispose();

        // 2. Usamos la referencia que guardamos para mostrar la original
        if (ventanaPadre != null) {
            ventanaPadre.setVisible(true);
        }
    }//GEN-LAST:event_btnSalirActionPerformed

    private void menuItemAdmVoluntariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemAdmVoluntariosActionPerformed
        FrmAdminVoluntarios adm = new FrmAdminVoluntarios(this,idRefugio);
        adm.setLocationRelativeTo(null);
        adm.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_menuItemAdmVoluntariosActionPerformed

    private void menuItemAdmAsignacionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemAdmAsignacionesActionPerformed
        FrmAdminAsignaciones adm = new FrmAdminAsignaciones(this,idRefugio);
        adm.setLocationRelativeTo(null);
        adm.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_menuItemAdmAsignacionesActionPerformed

    private void menuItemListaVoluntariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemListaVoluntariosActionPerformed

        FrmListaVoluntarios adm = new FrmListaVoluntarios(this);
        adm.setLocationRelativeTo(null);
        adm.setVisible(true);
        this.setVisible(false);

    }//GEN-LAST:event_menuItemListaVoluntariosActionPerformed

    private void menuItemListaAnimalesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemListaAnimalesActionPerformed

        FrmListaAnimales adm = new FrmListaAnimales(this,idRefugio);
        adm.setLocationRelativeTo(null);
        adm.setVisible(true);
        this.setVisible(false);
        
    }//GEN-LAST:event_menuItemListaAnimalesActionPerformed

    private void menuItemListaAsignacionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemListaAsignacionesActionPerformed

        FrmListaAsignaciones adm = new FrmListaAsignaciones(this, idRefugio);
        adm.setLocationRelativeTo(null);
        adm.setVisible(true);
        this.setVisible(false);

    }//GEN-LAST:event_menuItemListaAsignacionesActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSalir;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lblNombreRefugio;
    private javax.swing.JLabel lblRefugio;
    private javax.swing.JLabel lblUbi;
    private javax.swing.JMenu menuAnimales;
    private javax.swing.JMenu menuAsignaciones;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenuItem menuItemAdmAnimales;
    private javax.swing.JMenuItem menuItemAdmAsignaciones;
    private javax.swing.JMenuItem menuItemAdmVoluntarios;
    private javax.swing.JMenuItem menuItemListaAnimales;
    private javax.swing.JMenuItem menuItemListaAsignaciones;
    private javax.swing.JMenuItem menuItemListaVoluntarios;
    private javax.swing.JMenu menuVoluntarios;
    private javax.swing.JPanel pnlBase;
    // End of variables declaration//GEN-END:variables
}
