/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package views;

import controllers.RefugioController;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author valeria
 */
public class FrmRegistroRefugio extends javax.swing.JFrame {

    
    RefugioController rController;
    private javax.swing.JFrame ventanaPadre;
    /**
     * Creates new form FrmRegistroRefugio
     */
    public FrmRegistroRefugio(javax.swing.JFrame padre) {
        initComponents();
        this.ventanaPadre = padre;
        rController = new RefugioController();
        cargarTablaRefugios();
        btnEliminar.setVisible(false);
        this.setLocationRelativeTo(null); // Centra la ventana en la pantalla
        this.setResizable(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlPanelBase = new javax.swing.JPanel();
        pnlTituloSuperior = new javax.swing.JPanel();
        lblTituloSuperior = new javax.swing.JLabel();
        lblTituloAdmin = new javax.swing.JLabel();
        lblSubtituloRegistro = new javax.swing.JLabel();
        txtID = new javax.swing.JTextField();
        lblID = new javax.swing.JLabel();
        txtCapacidad = new javax.swing.JTextField();
        lblCapacidad = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        lblNombre = new javax.swing.JLabel();
        txtUbicacion = new javax.swing.JTextField();
        lblUbicacion = new javax.swing.JLabel();
        txtResponsable = new javax.swing.JTextField();
        lblResponsable = new javax.swing.JLabel();
        btnEliminar = new javax.swing.JButton();
        txtFiltro = new javax.swing.JTextField();
        lblSubtituloFiltro = new javax.swing.JLabel();
        scrlRefugios = new javax.swing.JScrollPane();
        tblRefugios = new javax.swing.JTable();
        btnRegistrar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        btnListo = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnlPanelBase.setBackground(new java.awt.Color(255, 255, 255));

        pnlTituloSuperior.setBackground(new java.awt.Color(204, 204, 204));

        lblTituloSuperior.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        lblTituloSuperior.setForeground(new java.awt.Color(102, 102, 102));
        lblTituloSuperior.setText("Refugios Cajeme");

        javax.swing.GroupLayout pnlTituloSuperiorLayout = new javax.swing.GroupLayout(pnlTituloSuperior);
        pnlTituloSuperior.setLayout(pnlTituloSuperiorLayout);
        pnlTituloSuperiorLayout.setHorizontalGroup(
            pnlTituloSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTituloSuperiorLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(lblTituloSuperior)
                .addContainerGap(677, Short.MAX_VALUE))
        );
        pnlTituloSuperiorLayout.setVerticalGroup(
            pnlTituloSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTituloSuperiorLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTituloSuperior)
                .addContainerGap(7, Short.MAX_VALUE))
        );

        lblTituloAdmin.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        lblTituloAdmin.setForeground(new java.awt.Color(102, 102, 102));
        lblTituloAdmin.setText("Administración Refugios");

        lblSubtituloRegistro.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        lblSubtituloRegistro.setForeground(new java.awt.Color(102, 102, 102));
        lblSubtituloRegistro.setText("Registrar un Refugio");

        txtID.setEditable(false);
        txtID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIDActionPerformed(evt);
            }
        });

        lblID.setText("ID:");

        lblCapacidad.setText("Capacidad:");

        lblNombre.setText("Nombre:");

        lblUbicacion.setText("Ubicación:");

        lblResponsable.setText("Nombre Responsable:");

        btnEliminar.setBackground(new java.awt.Color(81, 112, 255));
        btnEliminar.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        btnEliminar.setForeground(new java.awt.Color(255, 255, 255));
        btnEliminar.setText("ELIMINAR");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        txtFiltro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFiltroActionPerformed(evt);
            }
        });
        txtFiltro.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtFiltroKeyReleased(evt);
            }
        });

        lblSubtituloFiltro.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        lblSubtituloFiltro.setForeground(new java.awt.Color(102, 102, 102));
        lblSubtituloFiltro.setText("------- Filtrar por Nombre -------");

        tblRefugios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tblRefugios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblRefugiosMouseClicked(evt);
            }
        });
        scrlRefugios.setViewportView(tblRefugios);

        btnRegistrar.setBackground(new java.awt.Color(81, 112, 255));
        btnRegistrar.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        btnRegistrar.setForeground(new java.awt.Color(255, 255, 255));
        btnRegistrar.setText("REGISTRAR");
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });

        btnCancelar.setBackground(new java.awt.Color(81, 112, 255));
        btnCancelar.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        btnCancelar.setForeground(new java.awt.Color(255, 255, 255));
        btnCancelar.setText("CANCELAR");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        btnListo.setBackground(new java.awt.Color(0, 204, 102));
        btnListo.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        btnListo.setForeground(new java.awt.Color(255, 255, 255));
        btnListo.setText("LISTO");
        btnListo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlPanelBaseLayout = new javax.swing.GroupLayout(pnlPanelBase);
        pnlPanelBase.setLayout(pnlPanelBaseLayout);
        pnlPanelBaseLayout.setHorizontalGroup(
            pnlPanelBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlTituloSuperior, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlPanelBaseLayout.createSequentialGroup()
                .addGroup(pnlPanelBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlPanelBaseLayout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(pnlPanelBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlPanelBaseLayout.createSequentialGroup()
                                .addGap(144, 144, 144)
                                .addComponent(lblSubtituloRegistro))
                            .addGroup(pnlPanelBaseLayout.createSequentialGroup()
                                .addGroup(pnlPanelBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblCapacidad)
                                    .addComponent(lblID)
                                    .addComponent(lblNombre)
                                    .addComponent(lblUbicacion)
                                    .addComponent(lblResponsable))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(pnlPanelBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtUbicacion)
                                    .addComponent(txtNombre)
                                    .addComponent(txtResponsable, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtCapacidad)
                                    .addComponent(txtID)))))
                    .addGroup(pnlPanelBaseLayout.createSequentialGroup()
                        .addGap(118, 118, 118)
                        .addComponent(btnRegistrar)
                        .addGap(36, 36, 36)
                        .addComponent(btnCancelar)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlPanelBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlPanelBaseLayout.createSequentialGroup()
                        .addGroup(pnlPanelBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlPanelBaseLayout.createSequentialGroup()
                                .addGap(78, 78, 78)
                                .addComponent(lblSubtituloFiltro))
                            .addGroup(pnlPanelBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlPanelBaseLayout.createSequentialGroup()
                                    .addComponent(txtFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(77, 77, 77))
                                .addComponent(scrlRefugios, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 357, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(44, 44, 44))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlPanelBaseLayout.createSequentialGroup()
                        .addComponent(btnEliminar)
                        .addGap(170, 170, 170))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlPanelBaseLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnListo)
                .addGap(14, 14, 14))
            .addGroup(pnlPanelBaseLayout.createSequentialGroup()
                .addGap(294, 294, 294)
                .addComponent(lblTituloAdmin)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlPanelBaseLayout.setVerticalGroup(
            pnlPanelBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPanelBaseLayout.createSequentialGroup()
                .addComponent(pnlTituloSuperior, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblTituloAdmin)
                .addGap(37, 37, 37)
                .addGroup(pnlPanelBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlPanelBaseLayout.createSequentialGroup()
                        .addComponent(lblSubtituloRegistro)
                        .addGap(20, 20, 20)
                        .addGroup(pnlPanelBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblID)
                            .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pnlPanelBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblCapacidad)
                            .addComponent(txtCapacidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pnlPanelBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblNombre)
                            .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pnlPanelBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblUbicacion)
                            .addComponent(txtUbicacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pnlPanelBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblResponsable)
                            .addComponent(txtResponsable, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addGroup(pnlPanelBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnRegistrar)
                            .addComponent(btnCancelar)
                            .addComponent(btnEliminar)))
                    .addGroup(pnlPanelBaseLayout.createSequentialGroup()
                        .addComponent(lblSubtituloFiltro)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(scrlRefugios, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addComponent(btnListo)
                .addGap(14, 14, 14))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlPanelBase, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlPanelBase, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIDActionPerformed

    private void txtFiltroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFiltroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFiltroActionPerformed

    private void tblRefugiosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblRefugiosMouseClicked
        cargarDatosATxt();
    }//GEN-LAST:event_tblRefugiosMouseClicked

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
        guardarRefugio();
    }//GEN-LAST:event_btnRegistrarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        limpiarFormulario();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnListoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListoActionPerformed
        // 1. Cerramos el registro (se libera esta memoria)
        this.dispose(); 

        // 2. Usamos la referencia que guardamos para mostrar la original
        if (ventanaPadre != null) {
            ventanaPadre.setVisible(true);
        }
    }//GEN-LAST:event_btnListoActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        eliminarRefugio();
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void txtFiltroKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFiltroKeyReleased
        buscar();
    }//GEN-LAST:event_txtFiltroKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnListo;
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JLabel lblCapacidad;
    private javax.swing.JLabel lblID;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblResponsable;
    private javax.swing.JLabel lblSubtituloFiltro;
    private javax.swing.JLabel lblSubtituloRegistro;
    private javax.swing.JLabel lblTituloAdmin;
    private javax.swing.JLabel lblTituloSuperior;
    private javax.swing.JLabel lblUbicacion;
    private javax.swing.JPanel pnlPanelBase;
    private javax.swing.JPanel pnlTituloSuperior;
    private javax.swing.JScrollPane scrlRefugios;
    private javax.swing.JTable tblRefugios;
    private javax.swing.JTextField txtCapacidad;
    private javax.swing.JTextField txtFiltro;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtResponsable;
    private javax.swing.JTextField txtUbicacion;
    // End of variables declaration//GEN-END:variables

    private void cargarTablaRefugios(){
        tblRefugios.setModel(rController.obtenerTablaRefugios()); // -- Desde el controlador. Metodo obtenerTablaClientes()
        // Ese valor del metodo se setea en la tabla
    }
    
    private void guardarRefugio(){
        
        try{
            // 1. Tomar datos de los campos
            String nombre = txtNombre.getText().trim();
            String capacidadStr = txtCapacidad.getText().trim(); // Lo tomamos como String para validar
            String ubicacion = txtUbicacion.getText().trim();
            String responsable = txtResponsable.getText().trim();

            // 2. Ejecutar validación completa (Campos vacíos, Regex y números)
            if (!validarCampos()) {
                return; // Si validarCampos() muestra un error y devuelve false, nos detenemos aquí
            }

            // 3. Si pasó la validación, convertimos la capacidad a int con seguridad
            int capacidad = Integer.parseInt(capacidadStr);

            // 4. Lógica para GUARDAR (Insertar)
            if (btnRegistrar.getText().equals("REGISTRAR")) {
                boolean exito = rController.agregarRefugio(nombre, capacidad, ubicacion, responsable);
                if (exito) {
                    JOptionPane.showMessageDialog(this, "Refugio agregado con éxito");
                    cargarTablaRefugios(); // Refrescar tu tabla o lista
                } else {
                    JOptionPane.showMessageDialog(this, "Error al guardar el refugio", "Error", JOptionPane.ERROR_MESSAGE);
                }
            } 

            // 5. Lógica para ACTUALIZAR
            else if (btnRegistrar.getText().equals("ACTUALIZAR")) {
                int id = Integer.parseInt(txtID.getText().trim()); // Asegúrate de tener el ID para actualizar

                boolean exito = rController.editarRefugio(id, nombre, capacidad, ubicacion, responsable);
                if (exito) {
                    JOptionPane.showMessageDialog(this, "Refugio actualizado correctamente.");
                    cargarTablaRefugios();
                } else {
                    JOptionPane.showMessageDialog(this, "Error al actualizar el refugio.", "Error", JOptionPane.ERROR_MESSAGE);
                }
            }

            limpiarFormulario(); // Vaciar los TXT después de la operación exitosa
        } catch (Exception ex){
            JOptionPane.showMessageDialog(
                    this,
                    "Error: " + ex.getMessage(),
                    "Error",
                    JOptionPane.ERROR_MESSAGE
            );
        }
        
    }
    
    private boolean validarCampos() {
        // Validar que nada esté vacío (usando .isEmpty())
        if (txtNombre.getText().trim().isEmpty() || 
            txtCapacidad.getText().trim().isEmpty() || 
            txtUbicacion.getText().trim().isEmpty() || 
            txtResponsable.getText().trim().isEmpty()) {

            JOptionPane.showMessageDialog(this, "Todos los campos son obligatorios.");
            return false; 
        }

        // 2. Validar que la capacidad sea un número entero positivo
        String capTexto = txtCapacidad.getText().trim();
        if (!capTexto.matches("\\d+")) { // Regex: solo dígitos
            JOptionPane.showMessageDialog(this, "La capacidad debe ser un número entero (sin decimales).");
            return false;
        }

        try {
            int cap = Integer.parseInt(capTexto);
            if (cap <= 0) {
                JOptionPane.showMessageDialog(this, "La capacidad debe ser mayor a cero.");
                return false;
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "El número de capacidad es demasiado grande.");
            return false;
        }

        // 3. Opcional: Validar longitud mínima de nombres
        if (txtNombre.getText().trim().length() < 3) {
            JOptionPane.showMessageDialog(this, "El nombre del refugio es muy corto.");
            return false;
        }
        
        // Validar que el nombre del responsable solo tenga letras
        String resp = txtResponsable.getText().trim();
        if (!resp.matches("^[a-zA-ZáéíóúÁÉÍÓÚñÑ ]+$")) {
            JOptionPane.showMessageDialog(this, "El nombre del responsable solo puede contener letras.");
            return false;
        }

        // Puedes hacer lo mismo para el nombre del refugio si quieres ser estricto
        String nombreRef = txtNombre.getText().trim();
        if (!nombreRef.matches("^[a-zA-ZáéíóúÁÉÍÓÚñÑ 0-9]+$")) { // Aquí sí permito números por si es "Refugio 1"
            JOptionPane.showMessageDialog(this, "El nombre del refugio tiene caracteres no permitidos.");
            return false;   
        }
        
        return true; // Si llegó hasta aquí, ¡todo está perfecto!
    }
    
    private void cargarDatosATxt(){
        int fila = tblRefugios.getSelectedRow();
        if(fila>=0){
            txtID.setText(tblRefugios.getValueAt(fila, 0).toString());
            txtNombre.setText(tblRefugios.getValueAt(fila, 1).toString());
            txtCapacidad.setText(tblRefugios.getValueAt(fila, 2).toString());
            txtUbicacion.setText(tblRefugios.getValueAt(fila, 3).toString());
            txtResponsable.setText(tblRefugios.getValueAt(fila, 4).toString());

            btnRegistrar.setText("ACTUALIZAR");
            btnEliminar.setVisible(true);
            
        }
    }
    
    private void limpiarFormulario(){
        txtID.setText("");
        txtCapacidad.setText("");
        txtNombre.setText("");
        txtUbicacion.setText("");
        txtResponsable.setText("");
        txtFiltro.setText("");
        btnRegistrar.setText("REGISTRAR");
        btnEliminar.setVisible(false);
    }
    
    private void eliminarRefugio() {
        try {
            // Obtener el ID del campo
            if (txtID.getText().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Selecciona un refugio de la tabla primero.");
                return;
            }
            int id = Integer.parseInt(txtID.getText());

            // Preguntar
            int confirm = JOptionPane.showConfirmDialog(this, 
                    "¿Está seguro de querer eliminar este refugio?",
                    "Confirmar Eliminación", 
                    JOptionPane.YES_NO_OPTION,
                    JOptionPane.WARNING_MESSAGE);

            if (confirm == JOptionPane.YES_OPTION) {

                try {
                    // Llamada al controlador
                    boolean exito = rController.eliminarRefugio(id);

                    if (exito) {
                        JOptionPane.showMessageDialog(this, "Refugio eliminado con éxito");
                        cargarTablaRefugios();     
                        limpiarFormulario(); 
                    } else {
                        JOptionPane.showMessageDialog(this, 
                                "No se encontró el refugio a eliminar", 
                                "Error", 
                                JOptionPane.ERROR_MESSAGE);
                    }

                } catch (SQLException e) {
                    // Si el refugio tiene animales asignados
                    JOptionPane.showMessageDialog(this,
                            "No se puede eliminar: el refugio aún tiene animales asociados.",
                            "Restricción de Base de Datos",
                            JOptionPane.WARNING_MESSAGE);
                }   
            }       
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,
                    "Error al procesar la eliminación: " + e.getMessage(),
                    "Error",
                    JOptionPane.ERROR_MESSAGE);
        }
        
        
    }
    
    public void buscar(){
        String nombre = txtFiltro.getText().trim();
        if(nombre.isEmpty()){
            cargarTablaRefugios();
        } else {
            tblRefugios.setModel(rController.obtenerTablaRefugiosFiltroNombre(nombre));
        }
    }
}
